### ISSUE TITLE
Effect not triggered for ver 3.7

### ISSUE THREAD

**Issue by wizd** [mrpmorris/Fluxor#100]
Action dispatched but the effect method not fired for ver 3.7. I have to revert to ver 3.2 to make it works.

**Comment by mrpmorris** [comment]
I'll need an example project otherwise I'll have nothing to go on.

**Comment by wizd** [comment]
thank you for your reply. here is the project I'm working on now: https://github.com/LYRA-Block-Lattice/Lyra-Core/tree/master/Core/Nebula

to reproduce, use the web wallet, create new or restore by the private key, all action is handled by effects. if use 3.7, the button will do nothing.

**Comment by mrpmorris** [comment]
VS2019 won't load the Android or iOS projects. What do I need installed to get those to open?

**Comment by wizd** [comment]
> VS2019 won't load the Android or iOS projects. What do I need installed to get those to open?

unload all failed projects

**Comment by mrpmorris** [comment]
Sorry, I'll need a smaller test case. I had problems running the app (null reference when trying to do something to a block) and I don't have the time to get your app working.

Can you clone your app and then keep removing stuff until you have something very basic that won't fail to run on my laptop?

**Comment by wizd** [comment]
I found the bug, the Effect method mistakenly tagged protected, which should be public. The EffectWrapper can't find the method which was tagged protected. protected effect method works in v3.2 but not v3.7.

`		[EffectMethod]
		protected async Task HandleRestore(WebWalletRestoreAction action, IDispatcher dispatcher)
		{
		}`
