### ISSUE TITLE
Accessing State from within an Effect

### ISSUE THREAD

**Issue by rdeanmcdonald** [mrpmorris/Fluxor#101]
Hello! Thanks for this excellent library.

I had a question about accessing the current Fluxor State inside an effect method. My Blazor-server app let's a user interact with a peripheral device, and there's a scenario where the user might close the browser while the device is busy with something that I'd like to account for. The user starts the device with a StartDevice action. That action triggers an effect to communicate with the device. In the effect, when the async response from the device returns, I need to either a) update the UI to reflect the device status, or b) turn off the device if the user closed the browser. If the user closes the browser, I can fire an action to update the Fluxor State to "closed", but I somehow would like to get this state from that effect method. Is there a way to get the current Fluxor State from an effect method?

**Comment by mrpmorris** [comment]
You can inject the state into your effect class

public class MyEffects
{
  private readonly IState<MyState> State;

  public MyEffects(IState<MyState> state)
  {
    State = state;
  }

  [EffectMethod]
  public Task HandleBrowserClosed(MyAction action, IDispatcher dispatcher)
  {
    if (State.Value.Whatever)
    {
    }
  }
}

**Comment by rdeanmcdonald** [comment]
Awesome thank you!

**Comment by wdaniel1993** [comment]
@mrpmorris couldn't the example here produce race conditions? Or is that somehow considered?

In the example can I be sure that the state represents the state before being updated by reducers? 

If this is would be a problem, would it make more sense to include the state in the action.

**Comment by mrpmorris** [comment]
The effects do not execute until after all reducers have finished modifying the state.

**Comment by wdaniel1993** [comment]
Thanks for the quick response!

Just to clarify further:
- If two Actions are triggered microseconds from each other. Will the execution order be: reducers (action 1) -> effects (action 1) -> reducers (action 2) -> effects (action 2)? Or will Fluxor not wait for the effects to be finished (which would make the state unpredictable)?
- What you are saying also implies, if the state at the time of action execution (before reducers do their work) is needed, the best way to handle it is to include (parts of) the state in the action properties? Or is there a better way?

**Comment by hypdeb** [comment]
I'm facing a case where effects execute before reducers in a MAUI mobile app:
Action A triggers Effect A, which in turn dispatches Action B, which first triggers effect B and then is reduced into the state. The problem is that effect B would like the state to already be reduced by action B, but it's not. Maybe using this library in MAUI was a bit too out there?
