### ISSUE TITLE
Implementing a finite state machine

### ISSUE THREAD

**Issue by RicardoValero95** [mrpmorris/Fluxor#103]
Hi, big fan of your library. 
So I am not expecting someone else to do my work, but I'd appreciate it if someone guided me in the right direction. 

I am currently using Fluxor to manage the state of an app.
I am somewhat stuck on two issues:
- Finite state machine
- Stopwatch

My current FSM is just my fancy way of calling a switch case for managing sequential user inputs that call the different actions. Example: 
```csharp
switch (RepackState.Value.Step)
{
    case 0:
        Dispatcher.Dispatch(new FindPartAction(number: ScanInput));
        ScanInput = "";
        break;
    case 1:
        Dispatcher.Dispatch(new InputLotNumberAction(number: ScanInput));
        ScanInput = "";
        break;
     // etc.
}
```
My current stopwatch is pretty much the same as this one: https://github.com/DanielRBowen/TimeMage/blob/master/TimeMage/Client/Pages/StopWatchPage.razor
I haven't figured out an easy way to implement it with Fluxor. (Perhaps something like this? https://stackoverflow.com/questions/34577012/creating-a-stopwatch-with-redux)

Is it reasonable to use Fluxor for any of these cases? Any tips on how to implement this correctly?

**Comment by mrpmorris** [comment]
This will let you start/stop the automatic dispatching of an action every 1 second. Is this what you need?
```
public class StopWatchEffects
{
  private Timer? Timer;

  [EffectMethod]
  public Task HandleStart(StartAction action, IDispatcher dispatcher)
  {
    if (Timer != null)
      return;
    Timer = new System.Threading.Timer( _ => DoTick(dispatcher), null, 1000, TimeSpan.Zero);
  }

  [EffectMethod]
  public Task HandleStop(StopAction action, IDispatcher dispatcher)
  {
    Timer?.Dispose();
    Timer = null;
  }

  private void DoTick(IDispatcher dispatcher)
  {
    dispatcher.Dispatch(new TickAction());
  }
}
```

**Comment by RicardoValero95** [comment]
Yes 😄, thanks. 
Any idea on how to call sequential actions? 
I'm fairly new to flux / redux, I found this issue interesting: 
https://github.com/reduxjs/redux/issues/468

**Comment by mrpmorris** [comment]
```
Dispatcher.Dispatch(new Action1());
Dispatcher.Dispatch(new Action2());
Dispatcher.Dispatch(new Action3());
```

Or am I missing something in the question?

**Comment by mrpmorris** [comment]
I'm closing this for now. If there is anything else you need then please feel free to reopen it.
