### ISSUE TITLE
exception thrown from store initializer when using an environment other than Development

### ISSUE THREAD

**Issue by mikewiebel** [mrpmorris/Fluxor#104]
Server side blazor, .net core 3.1, latest and greatest..

I built a sample with state on the Counter as in the tutorial.  Everything works perfectly when I run with "Development" as the value for ASPNETCORE_ENVIRONMENT.  When I change to anything else ("Production") the store initializer throws an error on this line --

					bool success = await JSRuntime.InvokeAsync<bool>("tryInitializeFluxor");

(line 88)
error message -- Could not find 'tryInitializeFluxor' in 'window'

My launch settings change --      

"FluxorTesting_Production": {
      "commandName": "Project",
      "launchBrowser": true,
      "applicationUrl": "http://localhost:5000",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Production"
      }
    }

I tested the environment change against a newly generated Blazor app (counter, weather service); no issues.

Thanks in advance.  Really like this library.

**Comment by mrpmorris** [comment]
That error is usually a sign that the Fluxor js library source hasn't been included. Can you share the app on github?

**Comment by mikewiebel** [comment]
https://github.com/mikewiebel/FluxorTutorial

Thank you.

Launching with FluxorTutorial_Test produces the error.

**Comment by mrpmorris** [comment]
I just tried it with a new app.

1: New Blazor Server App (3.1)
2: New blazor class lib
3: Reference the class lib
4: Add a script reference to the default js file in the class lib
5: Edit properties/launchSettings.json
6: Change the name to appName_Production
7: Change the environment to production

404 error

Same steps worked correctly in .NET 5

**Comment by RoseberryPi** [comment]
This is an issue with how Blazor handles static files in a Production environment when running from the build output. What is actually happening is that the application can't see `_content/Fluxor.Blazor.Web/scripts/index.js`. Launch the application in the dev environment and you can see that navigating to `localhost:port/_content/Fluxor.Blazor.Web/scripts/index.js` returns the js file but when navigating to that page when in a production environment (or anything other than dev), there's nothing there. Follow the below to fix the issue.

See https://stackoverflow.com/questions/58862932/blazor-server-static-files-dont-link-in-non-dev-environments

Add `webBuilder.UseStaticWebAssets();` to your Program.cs file and everything should work again.

**Comment by mikewiebel** [comment]
You are correct.  One of my collogues figured it out months ago, I got busy and lost track of the issue.  Hopefully your comment will help out anyone else running into the issue.  Thanks.

**Comment by nhwilly** [comment]
Great package.  Just getting started with Blazor and Fluxor.

I'm not using a `hosted` approach.  I have a WASM and a stand alone API, so I can't seem to fix the problem as I don't have a `webBuilder`.

Sorry to be such a beginner, but how do you solve this for a stand alone WASM app that only has a `program.cs` and uses this:
```cs
var builder = WebAssemblyHostBuilder.CreateDefault(args);
```

**Comment by nhwilly** [comment]
I did some digging and it looks like I am required to use a  `hosted` approach.  Does this sound right?  TIA

**Comment by mrpmorris** [comment]
No, you don't need your client to be hosted.
