### ISSUE TITLE
Using nested objects as a state object

### ISSUE THREAD

**Issue by frenzy10012** [mrpmorris/Fluxor#11]
Hi!

When i use complex object (instance of class A) as a state object:

```
public class A
{
    public List<B> B_LIST { get; set; }
}

public class B
{
    public List<C> C_LIST { get; set; }
}

public class C
{
    public string Title { get; set; }
}
```

i always get value _**List<C> C_LIST**_ null. Is this by design?

**Comment by mrpmorris** [comment]
C_LIST is always null when you do what?

**Comment by mrpmorris** [comment]
Closing due to lack of response. It looks as though you aren't initialising your List instances, Fluxor won't do that for you.
