### ISSUE TITLE
Any way to make an action update part of the state, without changing all values in the state?

### ISSUE THREAD

**Issue by niem94** [mrpmorris/Fluxor#12]
Use case is that I have two booleans in my State, and I want to change one of them from true to false without changing the other (it should remember its previous value).

Problem is using the Reducers as explained in the docs one has to make a new state for every action, which forces me to set both booleans anew, so stakeholderExists will always be false after dispatching ReduceSetIsCreatableAction:

```csharp
[ReducerMethod]
public static StakeholderState ReduceSetIsCreatableAction(StakeholderState state, SetIsCreatableAction action) =>
            new StakeholderState(isCreatable: action.IsCreatable, stakeholderExists: false);
```

Is there any way I can change individual values and set the rest of the values from the previous state?

**Comment by mpp** [comment]
You have the original state as parameter of the reduce method

**Comment by niem94** [comment]
Lol, I totally overlooked that. Thank you :-)

**Comment by mpp** [comment]
No problem!
