### ISSUE TITLE
Is it possible to make Fluxor depend on .NETStandard v2.0  instead of .NetStandard v2.1

### ISSUE THREAD

**Issue by nguyenvuduc** [mrpmorris/Fluxor#122]
I am using Fluxor for my Xamarin Forms project. However, I found adding Fluxor will force me to upgrade my project to depend on .NET Standard 2.1. UWP haven't been ready for .NET Standard 2.1 yet.

**Comment by mrpmorris** [comment]
I can't see why not. I'll have a look.

**Comment by mrpmorris** [comment]
Can you give me a link to the SDK? Not 2.0.0 because that causes me build problems with my work app, I believe I need at least 2.0.3

**Comment by mrpmorris** [comment]
@nguyenvuduc Without the 2.0.3 SDK I cannot do this for you.

**Comment by nguyenvuduc** [comment]
Sorry, it took so long to reply you. Isn't .NET Standard 2.0 come with Visual Studio 2019? You can also find it from Nuget: https://www.nuget.org/packages/NETStandard.Library/.

At the moment, I have solved my issue by downloading Fluxor. Modified csproj's TargetFrameworks to netstandard2.0;netcoreapp3.0, and then fixed 2 places in your code to compatible with .Net standard 2.0. Then I made my project reference directly to Fluxor instead of using Nuget.

Thank you.

**Comment by mrpmorris** [comment]
Try 3.8.1-Beta-1

**Comment by nguyenvuduc** [comment]
I have tried Fluxor 3.9.0 on my Xamarin UWP project that requires .NET Standard 2.0. It works. Thank you.

**Comment by mrpmorris** [comment]
I'd love to see a demo
