### ISSUE TITLE
Index page does not update state after dispatching action

### ISSUE THREAD

**Issue by hasan-hasanov** [mrpmorris/Fluxor#123]
Hi,

I am fairly new to fluxor so this is more of a question than a bug. I was trying to make a simple authentication which checks browser's local storage for stored user data.
If there are any display the user's name in index page. 

After a lot of trial and error I simply could not find any solution on why my state does not update and how to make it work.

I can see with Redux dev tools that the state is updating but this update does not reflect on Index page.

Here is a dead simple application that illustrates the issue: [Issue.zip](https://github.com/mrpmorris/Fluxor/files/5444890/Issue.zip)

Steps to reproduce:
1. Start the application
2. Go to chrome dev tools -> Application -> LocalStorage -> Expand and click in the host url
3. Add "CurrentUser" key and {"FullName":"Test"} as value
4. Refresh the page.

Expected behavior:
Test is displayed in Index since the Index page on OnInitialized method dispatches an action to read this from local storage

Actual behavior:
State does not gets updated.

Can someone point out my mistake?
Thanks in advance!

**Comment by mrpmorris** [comment]
Your page is not re-rendering when your state changed. You either have to 

1. Descend your page from Fluxor Component
```
@inherits Fluxor.Blazor.Web.Components.FluxorComponent
```

or
2. Subscribed to State.StateChanged and call `InvokeAsync(StateHasChanged)` from that callback, and don't forget to unsubscribe when your component is Disposed

Option 1 is the easiest.
