### ISSUE TITLE
Add support for generic type parameter in Feature/Effects/Reducers

### ISSUE THREAD

**Issue by patvin** [mrpmorris/Fluxor#124]
Fluxor doesn't register the Feature/Effects/Reducers if the Action has generic type parameter. Please provide a way to work with generic type parameters in Fluxor

Thanks!

**Comment by mrpmorris** [comment]
For the time-being you'll need to create a class for each type....

```
public class PersonEffects: MyGenericEffects<Person>
{
}
```

**Comment by gbryer** [comment]
Is this planned feature on the road-map at all?

My main use-case would be to dynamically create a `IApiSuccessAction<MyApiRequestClass>` with reflection in my middleware 
that handles API web requests and dispatch that to my reducers.

Currently I am defining a class for each request/outcome combination and using an attribute to match what type it should be created as. This isn't ideal and requires a lot of boilerplate code.

Maybe there is a better way that I'm missing though?

**Comment by mrpmorris** [comment]
Can you put together a small example app so I can see exactly what you are doing?

**Comment by gbryer** [comment]
My bad, it was a unrelated issue.
