### ISSUE TITLE
Reducers are not called

### ISSUE THREAD

**Issue by arttobe** [mrpmorris/Fluxor#128]
Hello everyone,

I have an Blazor Serverside Project and want to implement Fluxor. The InitialState are displayed, but when I display an action the Reducers are not called.

`
    [ReducerMethod]
    public static RootState ReduceSetDataView(RootState state, SetDataViewAction action)
    {
      Console.WriteLine("set data view");
      return new RootState(
        action.DataView,
        state.PatientState,
        state.CaseState,
        state.MTaskState,
        state.TrialState,
        state.PatientContext);
    }
  

  public class ReducerSetDataView : Reducer<RootState, SetDataViewAction>
  {
    public override RootState Reduce(RootState state, SetDataViewAction action)
    {
      Console.WriteLine("set data view");
      return new RootState(
        action.DataView,
        state.PatientState,
        state.CaseState,
        state.MTaskState,
        state.TrialState,
        state.PatientContext);
    }
  }

`
I tried both versions.

I hope someone can help me

**Comment by mrpmorris** [comment]
Have you initialized the store by adding `<Fluxor.Blazor.Web.StoreInitializer/>` in your App.razor?

**Comment by arttobe** [comment]
Oh yead, this was it. Thank you very much! My fault...

**Comment by mrpmorris** [comment]
I still do that :)
