### ISSUE TITLE
Feature() being called after it is already initialized

### ISSUE THREAD

**Issue by richardrooks** [mrpmorris/Fluxor#129]
Environment: Blazor Server side, C#, .net core 3.1

Running through the application for the second time Fluxor updates values correctly; however, upon calling Dispatcher.Dispatch( new ChangeLoginAction(ap)) it updates the values correctly but after running through the update the LoginState gets initialized again calling LoginFeatures GetInitialized.

call stack:
![image](https://user-images.githubusercontent.com/24272932/98160134-c0ee0f80-1eab-11eb-8132-1106fe705bb3.png)

I am using Fluxor on another state/action and it works great. Not sure why this is happening.

**Comment by mrpmorris** [comment]
Is an external site doing the auth process, and then doing a redirect on your website?

**Comment by mrpmorris** [comment]
I'll need more information to solve this. I expect it is the external sign in process that is doing a "real" navigation.
