### ISSUE TITLE
Is it possible to await the HandleAsync method in Effects?

### ISSUE THREAD

**Issue by niem94** [mrpmorris/Fluxor#13]
I need the effect to be executed synchronously, but as HandleAsync is called by Fluxor, I am not sure If I can make it so? Is there any way to ensure an action and its effect is finished before going to the nextline where the Dispatcher is used?

**Comment by mpp** [comment]
I'm not understanding your problem, add an example please.

**Comment by niem94** [comment]
So for example in this code I am using the first Dispatcher to check if a Stakeholder exists, and it has an effect that sets the StakeholderExists to true. But that effect is executed asynchronously, which results in the StakeholderExists to retain its value false, and the DeleteStakeholderAction therefore never being fired.

```csharp
Dispatcher.Dispatch(new CheckStakeholderAction(stakeholder));
if (StakeholderState.Value.StakeholderExists)
{
    Dispatcher.Dispatch(new DeleteStakeholderAction(stakeholder));
}
```

I can solve this by using a the bool IsLoading and a while loop like so:
```csharp
Dispatcher.Dispatch(new CheckStakeholderAction(stakeholder));
while(StakeholderState.Value.IsLoading){
    //Do Nothing
}
if (StakeholderState.Value.StakeholderExists)
{
    Dispatcher.Dispatch(new DeleteStakeholderAction(stakeholder));
}
```

But It would be nice if I could instead await the HandleAsync method in my effect somehow.

**Comment by mpp** [comment]
Can't you dispatch that DeleteStakeholderAction at the end of the EffectMethod that handles CheckStakeholderAction?

If you need to distinguish if you're "CheckStakeholderAction" for deletion purpose, add a boolean property to the action so the effect knows if it needs to dispatch DeleteStakeholderAction or not.

This is the way Flux/Redux works. I suggest you to study that deeper and get more comfortable with the concepts.

**Comment by niem94** [comment]
Okay thank you, I will look into Redux more, and try what you propose here. I will try that 👍
