### ISSUE TITLE
After update to C# 9 - blazor hangs 

### ISSUE THREAD

**Issue by kierepka** [mrpmorris/Fluxor#132]
Hi

After switching to .net 5 and going to 9, I now have a problem:
1) I changed the state private set to init in classes
2) I set default values in these properties

Now, unfortunately, the application does not start, a memory error pops up.

Example of changes:
https://github.com/kierepka/OriinDictionary/blob/master/Store/BaseTerms/BaseTermsState.cs

I can reverse these changes, but I would like to know where is the problem?

**Comment by mrpmorris** [comment]
Try updating to release 3.9.0 (just released) as that is when .NET 5 support was added.

If that isn't the solution, and you are using ReduxDevTools, try turning that off.

If it is neither of these problems, then information from the popup would be useful.

**Comment by kierepka** [comment]
Thx - after update to 3.9 and RC 5 - problem is still this same.
There is no any popup - app is not loading.
`   builder.Services.AddFluxor(options =>
            {
                options
                    .ScanAssemblies(typeof(Program).Assembly);
                    //.UseReduxDevTools(); // For ReduxDevTool support. Recommended to remove this on Production
            });

            //builder.Services.AddFluxor(o => o
            //    .ScanAssemblies(typeof(Program).Assembly)
            //    .UseReduxDevTools()
            //    .AddMiddleware<LoggingMiddleware>()
            //    .UseRouting());`

**Comment by kierepka** [comment]
00aba1c6:0x572d Uncaught (in promise) RuntimeError: memory access out of bounds
    at strcmp (<anonymous>:wasm-function[109]:0x572d)
    at mono_class_get_field_from_name_full (<anonymous>:wasm-function[547]:0x10b3c)
    at mono_first_chance_exception_checked (<anonymous>:wasm-function[7456]:0x11d341)
    at mono_first_chance_exception_internal (<anonymous>:wasm-function[7455]:0x11d2bf)
    at mono_handle_exception_internal (<anonymous>:wasm-function[3945]:0x93a25)
    at mono_handle_exception (<anonymous>:wasm-function[3946]:0x94243)
    at interp_throw (<anonymous>:wasm-function[133]:0x5efc)
    at interp_exec_method (<anonymous>:wasm-function[2155]:0x48f93)
    at interp_runtime_invoke (<anonymous>:wasm-function[7861]:0x12efed)
    at mono_jit_runtime_invoke (<anonymous>:wasm-function[7346]:0x118e4d)

**Comment by kierepka** [comment]
> Try updating to release 3.9.0 (just released) as that is when .NET 5 support was added.

Done - this same problem

> If that isn't the solution, and you are using ReduxDevTools, try turning that off.

Done - this same problem

> If it is neither of these problems, then information from the popup would be useful.

Sent 

whole project https://github.com/kierepka/OriinDictionary

**Comment by mrpmorris** [comment]
Could you create it as a Blazor-Server app to see if that gives you more useful error information?

**Comment by kierepka** [comment]
I will try to remove my todays changes. It's seems to that this is no Fluxor problem (I just checked on yesterday code with upgrade to C#9 and new Fluxor and it's working).

**Comment by mrpmorris** [comment]
Try this
https://www.metaltoad.com/blog/beginners-guide-git-bisect-process-elimination

**Comment by hybrid-technologies-solutions** [comment]
@kierepka Any chance to share what do you find ? I encounter the very same issue : app is not loading with no error message.

Removing <Fluxor.Blazor.Web.StoreInitializer /> make it works.

I'm on Blazor Server

**Comment by hybrid-technologies-solutions** [comment]
Neverming, figured it out.
It seems that when I have a dependency injection error in an effect, Fluxor seems not to load anymore ...
