### ISSUE TITLE
Guidance needed on correct usage of state and local caching

### ISSUE THREAD

**Issue by danglingneuron** [mrpmorris/Fluxor#135]
Assuming Fluxor maintains the state objects in memory for the lifetime of the browser-tab until the user either refreshes the browser of closes it. So essentially, state stays stale until an effect reloads it from the server OR the user dispatches an "edit-action"

Scenario: I need to maintain a local cache for 2 item types. The first is a reference data (a list for a dropdown) that I don't want to be getting from the server every time and it may be used in several use cases - hence local caching. The second may be a transactional record but it may not change frequently. User A may change it at which point I may need to purge it from the local cache. If user B changes it I will have a callback from the server (SignalR) and I will need to purge from local cache (i.e. request it a new from the server). I may also need a time based cache - i.e. refresh/reload from server if local item has been there for 10 minutes. In a big LOB application with a bunch of reference data types and transactional types, I need to minimize server round-trips.

How do you propose handling this? 

Approach A: handle it in the UI - check the state for the data, if not loaded then dispatch load-action. Add additional variable in state for tracking stale time e.g. data is present in state but state.loadTime is greater than 10 minutes ago - so dispatch load-action to refresh state from server. 

Approach B:  Add a variable in action (forcereload:bool, cacheTime:int); inject state in the effect. the effect checks the state if data is already there, then just dispatch "loaded-action" and return the existing state in reducer, if forceload is true - then relaod anyway, if state.loadTime is greater than action.cacheTime, then reload as well.

Approach C:  Use a middleware but this doesnt look doable. The middleware doesnt have a mapping of actions/state and probably cant dispatch new actions.

**Comment by mrpmorris** [comment]
This is what I would do

1: An effect triggered by StoreInitialized. It checks local storage for values, if the values are there then it loads them and fires off an action to have those values reduced into state (e.g. SetSharedDataAction) - if the values aren't there then it fires off an action FetchSharedDataAction)

2: An effect triggered by FetchSharedDataAction which gets the data from the server and then dispatches SetSharedDataAction to have the values reduced into state.

3: An effect triggered by the action that reduces into state (SetSharedDataAction) that has a private System.Threading.Timer field (defaulted to null) and does the following

```c#
public class ReloadSharedDataEffect: Effect<SetSharedDataAction>
{
  private System.Threading.Timer Timer;
  private IState<YourRelevantState> State;

  public ReloadSharedDataEffect(IState<YourRelevantState> state)
  {
    State = state;
  }

  protected override Task HandleAsync(SetSharedDataAction action, IDispatcher dispatcher)
  {
    // Cancel any existing timer
    Timer?.Dispose(); 
   
    // Write current state to local storage
    await WriteValuesToLocalStorage().ConfigureAwait(false); 

    // Set a new timer that will fetch data from the server if not reduced within the next 20 minutes
    Timer = new System.Threading.Timer(
      () => Dispatcher.Dispatch(new FetchDataAction()),
      TimeSpan.Zero,
      TimeSpan.FromMinutes(20));
  }

  private async Task WriteValuesToLocalStorage()
  {
    var values = State.Value.Whatever;
    await LocalStorage.WriteAsyncOrWhateverItsCalled(values);
  }
}
```

**Comment by flipch** [comment]
@mrpmorris How would you deal with blazor server where store  inittialized doesn't happen before JSInterop capabilities?

Trying to load if available a theme preference for dark mode

**Comment by mrpmorris** [comment]
I'd probably not show any UI until I had loaded the state,  except a spinner or something.
