### ISSUE TITLE
Discussion: Named states

### ISSUE THREAD

**Issue by nightBaker** [mrpmorris/Fluxor#139]
I have big component, which is used twice on the same page, so these two components render two documents and each has his own state . 
I used fluxor state like container of this two documents states 
```
{
// documentId -> document
 Dictionary<long,DocumentState> States { get; set; }
}
```
However, it is not convinient to subscribe for such state from different components and understand that something changed in special one. 

Is it possible to have named state ? For example,

```
IState<DocumentState> state;

state.WithName("{DocumentId}").StateChanged += DocumentStateChanged

Dispatcher.Dispatch("StateName", new Action{})
```

**Comment by mrpmorris** [comment]
You could avoid FluxorComponent and subscribe manually. If the even triggers and State[DocumentId] is a new instance then call StateHasChanged.

**Comment by nightBaker** [comment]
@mrpmorris, so do I need always have oldDocumentState to know that it was changed ?

**Comment by mrpmorris** [comment]
Yes. If it is immutable then you can just compare object references.
