### ISSUE TITLE
The dispatcher.Initialized.Status is set to RanToCompletion

### ISSUE THREAD

**Issue by amarkwong** [mrpmorris/Fluxor#14]
Hi,

I've a razor page like this

```razor
@inject IDispatcher Dispatcher

<form action="/">
	<input @bind="_email" type="text" placeholder="Enter your email">
	<input @bind="_password" type="password" placeholder="Enter your password">
	<button @onclick="OnSignIn">Sign In</button>
</form>
@code{
	public string _email {get;set;}
	public string _password {get;set;}
	public void OnSignIn ()
	{
		Dispatcher.Dispatch(new LoginAction(_email,_password));
	}
}
```

While debugging I realised the Dispatcher.Initialized.Status was WaitingForActivation  on the init, but will turn to RanToCompletion when the OnSignIn function is fired. And on the Effect file I cannot handle an async request to the back-end as the Task is complete.

What should I do to avoid this?

**Comment by mrpmorris** [comment]
Can you submit an example project?

**Comment by amarkwong** [comment]
Thanks for you reply. I've put my sample code on [my repo](https://github.com/amarkwong/FluxorDehttps://github.com/amarkwong/FluxorDemomo)

On the Login page, the Dispatcher.Initialized.Status is RanToCompletion when the OnSignIn function is triggered. This will cause the failure of any further Effect with async request.
![image](https://user-images.githubusercontent.com/6657590/78883333-ba75f180-7a9c-11ea-9251-f41d1d52764a.png)

**Comment by amarkwong** [comment]
Sorry, my bad, it is not a Fluxor issue
