### ISSUE TITLE
Any chance using JavaScript isolation ?

### ISSUE THREAD

**Issue by hybrid-technologies-solutions** [mrpmorris/Fluxor#140]
As I was looking for .NET 5 CSS isolation, I found this article :
https://www.meziantou.net/javascript-isolation-in-blazor-components.htm

Any chance you can use this technique for Fluxor to make import and use more easy ?

**Comment by mrpmorris** [comment]
If I did I'd probably have to stop supporting net standard 2.1 which I don't think is worth it.

I could probably support both, but I don't think it's worth the effort just so we don't have to add a <script> to our html.
