### ISSUE TITLE
Using fluxor on the Shared Lib of Blazor

### ISSUE THREAD

**Issue by cmorgado** [mrpmorris/Fluxor#141]
I'm trying to use Fluxor in the share Library but I'm not able due to some initialization error... any pointers to be able share between different Blazor apps

**Comment by mrpmorris** [comment]
What is the error and the call stack?

**Comment by cmorgado** [comment]
Well, I'm sorry but it seems the problem was between the chair and the keyboard ... I've moved back the Store to the shared project even renamed the namespace accordingly and now all works :)

Just a word: FANTASTIC library it changed my view on state management and I'm still learning !

**Comment by cmorgado** [comment]
re-tested and can't find a way to properly get it to work :(

**Comment by mrpmorris** [comment]
ScanAssemblies is a comma delimited list,  you only need to scan assemblies with Fearures/Effects/Rescuers in.

typeof(ClassInSharedAssembly).Assembly

**Comment by cmorgado** [comment]
thanks its perfect!..

**Comment by vpetkovic** [comment]
I am facing the same issue in Blazor Server (.NET6) where I have CL and all my fluxor classes are in it. When trying to build I get this `error CS0246: The type or namespace name 'App' could not be found (are you missing a using directive or an assembly reference?)`. when i comment out `options.ScanAssemblies(typeof(ClassInSharedAssembly).Assembly);` it builds but cannot resolve features `Unable to resolve service for type 'Fluxor.IFeature`1...`

Any clues?
