### ISSUE TITLE
Move dependency injection to separate package

### ISSUE THREAD

**Issue by KuraiAndras** [mrpmorris/Fluxor#142]
This would enable Fluxor to be used with other DI frameworks (for example Autofac).

**Comment by KuraiAndras** [comment]
Given the first implementation I did, it might be even better to create another package, something like Fluxor.DependencyInjection. This package would abstract away common tasks when working with DI and enable an easier implementation for other DI frameworks

**Comment by mrpmorris** [comment]
Isn't autofac compatible with IServiceCollection and IServiceProvider?

**Comment by KuraiAndras** [comment]
Yes, it is compatible, but some projects have the ability use different DI containers natively, without the Microsoft provided library, for example AutoMapper, and MediatR does this.
Right now, I want to try this with Unity 3D in WebGL, with [Extenject](https://github.com/svermeulen/Extenject), which provides reflection baking for better performance.

**Comment by mrpmorris** [comment]
Is there an extension library for that which will mediate with the MS libraries?

MS added that abstract library so people can choose which DI to use. That library should be compatible with the DI standard. I'm not keen on changing Fluxor to cater for its shortcomings.

**Comment by KuraiAndras** [comment]
That an understandable point. Close the issue, and the pr if you would like.

**Comment by mrpmorris** [comment]
I do appreciate you wanting to contribute though,  thank you!

**Comment by KuraiAndras** [comment]
If want to salvage something from the PR, I have created a .props file to make project files simpler.

**Comment by mrpmorris** [comment]
Could you explain it to me? It's something new to me and I'm really interested to learn :)

**Comment by KuraiAndras** [comment]
.props files are picked up by MsBuild, and with them you can create common project properties. Props files are applied hierarchically. 
I extracted common properties, from the .csproj files (version, author, project site, logo, license, etc), so when you want to change something (version, license, etc) you would only need to update it at one place. This also makes project files under common props smaller and less noisy.
You can read up on them [here](https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2019).

**Comment by mrpmorris** [comment]
Thank you very much.  I am now cleverer :)

If you'd like to submit a PR with just the props changes in I'd be happy to accept it!

**Comment by mrpmorris** [comment]
Merged, thanks for your contribution, I appreciate it!
