### ISSUE TITLE
DisposableCallback with Id "StateSubscriber.Subscribe" was not disposed

### ISSUE THREAD

**Issue by cmorgado** [mrpmorris/Fluxor#145]
Hi 
I have the strangest of errors.
as I navigate through my app all works fine but without any pattern, I get the `DisposableCallback with Id "StateSubscriber.Subscribe" was not disposed ` Error.

The strangest is it comes on pages that on the first load if was ok.
It's random
[localhost-1606920594748.log](https://github.com/mrpmorris/Fluxor/files/5630057/localhost-1606920594748.log)

Any tips to debug this?

**Comment by cmorgado** [comment]
Found the problem by looking at you periodic table game.
I had all the discpach calls in the OnInitialized changed it to OnAfterRender and now it works properly .
I started with this tutorial: https://betweentwobrackets.dev/posts/2020/06/state-management-with-blazor-using-fluxor-part-1/ ... :(

**Comment by mrpmorris** [comment]
OnInitialized is better. The exception should give you a link to this document, which describes your error

https://github.com/mrpmorris/Fluxor/blob/master/Docs/disposable-callback-not-disposed.md

In short, always call base when you override non-abstract methods.
