### ISSUE TITLE
Lacks options in ReduxDevTools

### ISSUE THREAD

**Issue by Ammonix** [mrpmorris/Fluxor#149]
As specified in: https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md
It should be possible to pass on an additional ```options``` object to the extension method:
```C#
public static Options UseReduxDevTools(this Options options);
```
Currently it's not possible to define ReduxDevTool behavior like [maxAge](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#maxage).

**Comment by remo87** [comment]
I'm tried using the same helper method and it seems it's not available in the current version. It seems like the only middleware currently available is the Routing one.

**Comment by mrpmorris** [comment]
Release 4.0, thanks!
