### ISSUE TITLE
Guidance requested - where should this logic be located in a fluxor based system?

### ISSUE THREAD

**Issue by bradtwurst** [mrpmorris/Fluxor#154]
I have a blazor server project that I am migrating to dotnet5.0

As part of this migration, I am migrating to the microsoft.identity.web packages for authentication/authorization logic.

With this package, Microsoft has introduced a method to handle authentication exceptions that may occur when retrieving data from an api call.  The documentation for this is located at https://github.com/AzureAD/microsoft-identity-web/wiki/Managing-incremental-consent-and-conditional-access#in-blazor-server

The main code logic is 

```csharp
protected override async Task OnInitializedAsync()
    {
        try
        {
            // downstreamAPI.CallWebApiAsync retrieve the access token, but may throw an auth exception
            apiResult = await downstreamAPI.CallWebApiAsync("blah");
        }
        catch (Exception ex)
        {
            ConsentHandler.HandleException(ex);
        }
    }

```

So, the logic above calls the consent handler when an auth exception occurs.  Of course, this is all done directly within the blazor page.

I am using fluxor and my multiple api calls (all which could fail with this exception) are within fluxor effects methods.

What would be the appropriate way to structure the logic flow of handling the auth exceptions?

I have a few different ideas, but I don't know if I like any of them.

1) in the [EffectMethod], handle the exception and call the ConsentHandler method directly within the method
2) in the [EffectMethod], handle the exception and dispatch an 'AuthFailureAction' that would itself be handled within an EffectMethod to call the ConsentHandler method
3) in the [EffectMethod], handle the exception, dispatch an '<specificApi>AuthFailureAction' that would be reduced for the specific UseCase state and store the Exception on the state, which could then be evaluated directly in the blazor page template to call the ConsentHandler
4) similar to 3), but have the page subscribe directly to the dispatch action event and handle the exception in code behind for the blazor page

Thoughts?  Not really sure what is the correct path to take.

Thanks,
James

**Comment by mrpmorris** [comment]
If have a service for calling the api and put it in there,  then use that service from your effects, would that work okay for you?

**Comment by jbradt-stiles** [comment]
thanks for the feedback - that appears to be a viable solution -  there may still be some gotchas as the ConsentHandler triggers navigation under the covers, but I haven't found them yet.
