### ISSUE TITLE
Using fluxor with a .net 5 MVC app with blazor components

### ISSUE THREAD

**Issue by swidurs** [mrpmorris/Fluxor#155]
Hi, 

I might be abusing fluxor a bit, so I just want to make sure if it can work as I intend it to or if i need to take a different approach.

My idea was to have a ProductState populated by my MVC Controller and then on the page is .cshtml there are 5 blazor components which need to read and maintain the ProductState (select one thing on one component and 3 others need to update, like that)

My problem is that my ProductState never gets populated from my MVC Controller.
The components just get the default state, not the one where I dispatched the intial values to. 
My ReducerMethod does not seem to get called, at least my breakpoint is not hit... 
I am just using a Dispachter.Dispatch(ProductActionSetInitialParameters).

Am I totally abusing fluxor, and this can just never work, or am I just missing something?
I initialize the store in startup Configure like: store.InitializeAsync().Wait();

Thanks for any help! :)

**Comment by mrpmorris** [comment]
Will they all get the same scope?

Try adding a constructor to your Feature and writing out the current time. If it happens twice then the page and the components have different scopes.

**Comment by swidurs** [comment]
Hi Mr. Morris,

thanks for your help.
I added a timestamp to the default constructor and a Console.WriteLine.

this is the output::
**Initialized default @21.01.2021 07:23:11**
Hosting environment: Development
Content root path: C:\Development\Arduvi\ARDUVI
Now listening on: https://localhost:55550
Application started. Press Ctrl+C to shut down.
**Initialized default @21.01.2021 07:23:31**
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]

So it gets initialized twice, the first is most likely the store.InitializeAsync().Wait(); in startup.cs.
The second one seems to be during the Method in my controller, the nothing till the exception when my blazor component tries to read from the store.

So my guess would be that it is the same scope, but the Dispatcher.Dispach() does not fire... 

If I set a breakpoint after the dispatcher, the debugger shows the following:
_dispatcher = {Fluxor.Store}
  Features = Count = 1
  Initialized = Id = 7080, Status = WaitingForActivation, Method = "{null}", Result = "{Not yet computed}"

Is this correct?
How can i check if the dispatcher is actually doing somthing?

**Comment by mrpmorris** [comment]
If the feature is being initialized twice then you must be getting a different scope for your page and components. Can you check if that is the case?

**Comment by swidurs** [comment]
I think the first initialisation comes from the line in startup.cs in the Configure Method. Since it happens even before kestrel starts... 
I do not have an app.razor, so i put the store.InitializeAsync().Wait() in startup.cs.

So no I do not think that the page and the components are in a diefferent scope.
I also added some Console.Writline to other store constructors, but they never get called...

**Comment by swidurs** [comment]
I tried a few more things, and now I think you are right. The store does get initialized twice...

**Comment by swidurs** [comment]
So I gess this cannot work. I will try a Blazor Component with child components now. The parent loads the values in the state, and the children read and change it.

**Comment by swidurs** [comment]
I moved all code from my MVC Controller into a blazor component whis is supposed to load the intial values into the state.
THis component has 2 child components which use the state. 

unfortunately I still see 2 initialisations, one from the parent component and another one later. 

I also removed the store.InitializeAsync().Wait() from the startup.cs, which removed the initialisation of the store before kestrel started...

**Comment by swidurs** [comment]
So I did not get very far. 
I added the logging middleware (logging is alwas good).

I seem to have loads of IStores... 

**Initialized default @21.01.2021 17:42:03** - gets called from host.Run() in Programm.cs - no idea why - no logging
Initializing store in startup cs - this one is OK, also logging via middleware
InitializeAsync
AfterInitializeAllMiddlewares
MayDispatchAction: StoreInitializedAction {}
BeforeDispatch: StoreInitializedAction {}
AfterDispatch: StoreInitializedAction {}
        ===========STATE AFTER DISPATCH===========
        Product: {
          "MaximumStateChangedNotificationsPerSecond": 0,
          "State": {
            "CustomerOrderId": null,
            "User": null,
            "ProductGroupId": null,
            "IsEditable": false,
            "ShowSupplierFilter": false,
            "SelectedFacets": [],
            "SelectedFinishings": [],
            "SelectedSupplier": [],
            "SelectedProject": null,
            "Width": 0.0,
            "Height": 0.0,
            "Length": 0.0,
            "ShippingCosts": 0,
            "FacetGroups": [],
            "Finishings": null,
            "FinishingVisualGroups": null,
            "IsLoading": true,
            "Initialized": "2021-01-21T17:42:03.8984203Z"
          }
        }

Initialized
Hosting environment: Development
Content root path: D:\Development\Arduvi\ARDUVI
Now listening on: https://localhost:55550
Application started. Press Ctrl+C to shut down.
Initialized default @21.01.2021 17:42:22 - when the first blazor control gest instatiated on the page - no idea why and no logging
Initialized default @21.01.2021 17:42:33 - out of thin air - no idea why and no logging

Thanks for any help

**Comment by mrpmorris** [comment]
If you can give me access to a repo I'll have a look for you

**Comment by swidurs** [comment]
My repo is on AzureDevops. I can give you access there. 
But the project is quite large, maybe we can do liveshare or something like this. I guess it might me easier ?

**Comment by swidurs** [comment]
After much reading I came to the following conclustion (please do correct me if I am wrong)

The MVC App creates a store and initializes it correctly with the line store.InitializeAsync().Wait() in startup.cs.
The service is created as scoped, so it will be recreated whenever a new connection http request to the server is made, hence the initializeAsync in startup.cs is useless...

I need to initialize every instance of the service. 
In a pure blazor server app this seems to be done in the App.razor with <Fluxor.Blazor.Web.StoreInitializer/>

Since in a MVC project there is no app.razor I need to initialze the store somwhere else. And it needs to be the store the blazor components will get injected. So far every component seems to have its own scope and its own state...

**Comment by mrpmorris** [comment]
I'm sorry, but I'm not familiar with running Blazor components inside ASP MVC.

**Comment by swidurs** [comment]
Thanks for your help. I could not find a way to make it work, so I gave up and I am using [https://github.com/cpear/BlazorComponentBus] (https://github.com/cpear/BlazorComponentBus) now. Its not as elegant but it works :)

**Comment by mrpmorris** [comment]
I think the problem here is that effects (which typically fetch data) are executed asynchronously in the background.

So you dispatch an action, the effect is queued up, the dispatch completes, you return your response, then the effect completes and updates the state.

Fluxor is designed to work with state you hold onto, not transient state like in MVC. I don't think this is going to work.
