### ISSUE TITLE
Guidance on state object, flat vs hierarchical 

### ISSUE THREAD

**Issue by agnauck** [mrpmorris/Fluxor#157]
I need some guidance on designing the state for optimal performance. I want to eliminate unnecessary updates when possible.
Lets consider a simple trading application where you monitor some different stock symbols on the screen. Where every stock has buy and sale transactions coming in (Trades).

Option A:
* StockStore
   * IEnumerabe<Stock> Stocks
      *  IEnumerabe<Trades> Trades

Option B:
* StockStore
   * IEnumerabe<Stock> Stocks
* TradeStore
   *  IEnumerabe<Trades> Trades

In a Vue or React app I would go with option B. In Vue.js for example there are **computed properties** which can get bounded to components.
So I could bind the following to my models:
```
IEnumerabe<Trades> TradesForStockMicrosoft = TradeStore.Where(t => t.Symbol == "MSFT")
IEnumerabe<Trades> TradesForStockApple = TradeStore.Where(t => t.Symbol == "AAPL")
```
When there are new trades getting inserted for Apple in the TradeStore, then the UI components bound to TradesForStockMicrosoft are not getting notified for updates and don't do unnecessary work.
In ReactiveUI there are similar concepts.

I am wondering how to deal with that in Fluxor and need some guidance.
How does it work when I bind to only a subset of data in my IEnumerabe based on a Linq query/predicate/condition.

Thanks,
Alex

**Comment by mrpmorris** [comment]
If you only want to show stocks and then their trades then option A is better.

If you additional want to show a list of trades the it would probably be better to go for option B.

It's just in-memory data, you have to decide what you want to do with it and which is the best structure to allow you to do that.

**Comment by agnauck** [comment]
I need to slice and dice the data in all components. So every component is showing a subset of data.
Like
* only trades for stock A
* only trades for stock B
* Counts of trade where some condition is met

My assumption is (which can be wrong) that FluxorComponent call StateHasChanged whenever something changes in my state. 
Should I be concerned about those StateHasChanged  performance wise when I use the same state in many small components within the application?

**Comment by mrpmorris** [comment]
You are correct, FluxorComponent will re-render whenever the state it observes alters.

If this isn't the behaviour you want, then instead of descending from FluxorComponent you should override `OnInitialized` and subscribe to the StateChanged event of each of your `IState<T>` properties.

When you are notified, you can check if the sub-section of state you are interested in has changed, and if it has then call `StateHasChanged()`.

**NOTE**: You should also implement `IDisposable` and unsubscribe from the `IState<T>.StateChanged` event, to avoid memory leaks.
