### ISSUE TITLE
Features are ignored if a middleware is in the same namespace

### ISSUE THREAD

**Issue by koryphaee** [mrpmorris/Fluxor#159]
I was testing something and put all the files (state, action, feature, middleware) into the same file (and therefore also the same namespace). I was pulling my hair out trying to find out why the IFeature<State> couldn't be resolved. For some unknown reason it worked when I commented out the middleware, even though I didn't add the middleware and it was never used.

Then I looked through the your code and found the reason: middlwares are being ignored when finding features and the like. This is implemented by finding all namespaces containing a middleware and ignoring all classes from those namespaces. That's the cause for the weird behaviour I experienced.

I know that an actual project probably won't have the middlewares in the same folder/namespace as a feature but I still think it should be handled differently. The exclusion has to work more specific to avoid ignoring too many types. I think the easiest way would be to ignore specific types instead of whole namespaces. This will be a bit slower if there are many middlewares but the entire dependency injection scanning is just raw reflection so this won't make a noticable difference.

Apart from this small issue I really like the library and look forward to working with you to fix this.
If you agree with my proposed solution please let me know and I will submit a pull request.

**Comment by mrpmorris** [comment]
I don't understand your suggested change. 

The library works this way so that state, effects, and reducers that accompany middleware aren't added to the store unless you include the middleware. 

The routing middleware is a good example of this.

**Comment by mrpmorris** [comment]
I'll close this for now. If you want to elaborate further then I'll re-open.
