### ISSUE TITLE
IDispatcher docs: Return type `void` documented as Task

### ISSUE THREAD

**Issue by amis92** [mrpmorris/Fluxor#16]
`IDispatcher.Dispatch` documentation comment has a `remarks` section about return type, which is no longer applicable (it's about Task, now it's void).

https://github.com/mrpmorris/Fluxor/blob/c6067bcea3376dfdb652a5a1fda581629fd09e9f/Source/Fluxor/IDispatcher.cs#L14

**Comment by mrpmorris** [comment]
Thank you!

**Comment by mrpmorris** [comment]
Fixed :)
