### ISSUE TITLE
Crash in mono runtime

### ISSUE THREAD

**Issue by gnagn** [mrpmorris/Fluxor#160]
I'm not sure if this is an issue with Fluxor or not, but it occurs if I inject an IDispatcher in a certain way and doesn't occur if I remove the IDispatcher constructor parameter.

This is a Blazor WebAssembly project. When run, it crashes with `Assertion: should not be reached at /__w/1/s/src/mono/mono/metadata/class.c:2213`

The issue seems to occur when you have a class that takes an IDispatcher in its constructor, and that class is injected into the constructor of a class that has an EffectMethod in it. If you remove the IDispatcher from the first class' constructor, you get no error, and if you remove the first class from the Effect class' constructor, you also get no error.

Making minor changes to the codebase such as adding markup to the component or removing the body from the action class change the error that appears. I've seen memory access out of bounds errors, and different should not be reached errors.

Here's a minimal example:

Program.cs:
```
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
using Microsoft.Extensions.DependencyInjection;
using System.Reflection;
using System.Threading.Tasks;
using Fluxor;

namespace FluxorProblem
{
	public class Program
	{
		public static async Task Main(string[] args)
		{
			var builder = WebAssemblyHostBuilder.CreateDefault(args);
			builder.RootComponents.Add<App>("#app");

			builder.Services.AddScoped<IInterop, Interop>();
			builder.Services.AddFluxor(options =>
			{
				options.ScanAssemblies(Assembly.GetExecutingAssembly());
			});
			await builder.Build().RunAsync();
		}
	}

	public record MyState
	(
		int Value
	);

	public class MyFeature : Feature<MyState>
	{
		public override string GetName() => "MyFeature";

		protected override MyState GetInitialState()
		{
			return new MyState(0);
		}
	}

	public class IncrementAction
	{
		public int Amount { get; }
		public IncrementAction(int amount) => Amount = amount;
	}

	public class IncrementEffects
	{
		public IncrementEffects(IInterop interop)
		{

		}

		[EffectMethod]
		public Task IncrementAction(IncrementAction action, IDispatcher dispatcher)
		{
			return Task.CompletedTask;
		}
	}

	public interface IInterop
	{
	}

	public class Interop : IInterop
	{
		public Interop(IDispatcher dispatcher)
		{
		}
	}
}
```

MainLayout.razor:
```
@inherits Fluxor.Blazor.Web.Components.FluxorLayout

@Body
```

Index.razor:
```
@page "/"

<MyComponent />
```

MyComponent.razor:
```
@inherits Fluxor.Blazor.Web.Components.FluxorComponent
```

[FluxorProblem.zip](https://github.com/mrpmorris/Fluxor/files/5921560/FluxorProblem.zip)

**Comment by mrpmorris** [comment]
The dispatcher is given to the effect as a parameter because injecting will cause a circular dependency.

Dispatcher needs store, store needs effects, therefore effects cannot dependency inject dispatcher.

I would say have your other class return what it needs dispatched and let the effect do the dispatching.

**Comment by gnagn** [comment]
Thanks for your response. The actual issue was in a more complicated scenario, and it took a while to even realize it had to do with the dispatcher. Reducing it to just this was fun. An unreachable code assertion in the runtime isn't much to go on.

I've since managed to work around it. The problem class was a js interop class that was communicating both ways with the js. Splitting it out into two classes that cover the Blazor -> js and js -> Blazor communication fixed the problem.

I wanted to make sure I'd understood the issue and there wasn't something else waiting to bite me down the road. Thanks for your help.

**Comment by Sequa** [comment]
> Thanks for your response. The actual issue was in a more complicated scenario, and it took a while to even realize it had to do with the dispatcher. Reducing it to just this was fun. An unreachable code assertion in the runtime isn't much to go on.
> 
> I've since managed to work around it. The problem class was a js interop class that was communicating both ways with the js. Splitting it out into two classes that cover the Blazor -> js and js -> Blazor communication fixed the problem.
> 
> I wanted to make sure I'd understood the issue and there wasn't something else waiting to bite me down the road. Thanks for your help.

I have run into this same issue. Could you please share more details on how you resolved it? Thanks.

**Comment by mrpmorris** [comment]
You cannot directly or indirectly inject IDispatcher into an effect, it causes a circular reference.
