### ISSUE TITLE
Effect<MyAction> HandleAsync override is protected which makes testing difficult

### ISSUE THREAD

**Issue by brettwinters** [mrpmorris/Fluxor#161]
Hi @mrpmorris 

Would it be possible to make the override public for ease of testability:

```c#
public class MyActionEffect : Effect<MyAction>
{
	protected override async Task HandleAsync(
              MyAction action, 
              IDispatcher dispatcher)
	{
		//...
	}
}
```

same as `Reducer<IState, MyAction>` which is `public override CounterState Reduce(MyState state, MyAction action)`

**Comment by mrpmorris** [comment]
Release 4.0
