### ISSUE TITLE
Feature request: Customize JsonConvert in ReduxDevTools

### ISSUE THREAD

**Issue by Pjotrtje** [mrpmorris/Fluxor#168]
Hello!
I was wondering wheter it would be possible to override the current deserialization/serialization of state in ReduxDevTools. Maybe add a custom Serialization Settings to ReduxDevToolsMiddlewareOptions? 

And, if possible be able to choose wheter to use Newtonsoft.Json or System.Text.Json.

Refit solved this with an adapter. See:
https://github.com/reactiveui/refit/blob/main/Refit/SystemTextJsonContentSerializer.cs
https://github.com/reactiveui/refit/blob/main/Refit.Newtonsoft.Json/NewtonsoftJsonContentSerializer.cs
Maybe here we could do something simular?

The reason for this feature request is that, because I have some complex objects which, when I timetravel in ReduxDevTools result in errrors. And if I could reuse my converters which I use in Refit (which are System.Text.Json) that would even be more awesome!

**Comment by mrpmorris** [comment]
I think I could add some way of letting you control json from the options

**Comment by mrpmorris** [comment]
I've just released 4.1-Beta1, could you give it a try?

Instructions are here
https://github.com/mrpmorris/Fluxor/tree/release/4.1/Tutorials/02-Blazor/02D-ReduxDevToolsTutorial#controlling-json-options

You have access to the `IServiceProvider` in the (optional) function that is executed to create the Json Options/Settings object too, in case you need that.

**Comment by Pjotrtje** [comment]
Nice! That was quick. I tested it with UseSystemTextJson and my customer converters and worked like a charm 👍 .

**Comment by mrpmorris** [comment]
Thanks for letting me know!
