### ISSUE TITLE
Effect<StoreInitializedAction>doesnt always get handled

### ISSUE THREAD

**Issue by HannahKiekens** [mrpmorris/Fluxor#171]
* TargetFramework: net5.0
* Fluxor.Blazor.Web: 4.0.0
* Microsoft.AspNetCore.Components.WebAssembly: 5.0.3

I am trying to get a reliable chain of API calls to "Start" my application
I have the following code:

``` C#
    public class StoreInitializedEffect : Effect<StoreInitializedAction>
    {
        private AuthenticationStateProvider AuthenticationStateProvider;
        private NavigationManager Navigation;

        public StoreInitializedEffect(AuthenticationStateProvider authenticationStateProvider, NavigationManager navigation) =>
            (AuthenticationStateProvider, Navigation) = (authenticationStateProvider, navigation);

        public override async Task HandleAsync(StoreInitializedAction action, IDispatcher dispatcher)
        {
            var authState = await AuthenticationStateProvider.GetAuthenticationStateAsync();
            var user = authState.User;
            
            if (user.Identity.IsAuthenticated == false)
            {
                Navigation.NavigateTo($"authentication/login?returnUrl={Uri.EscapeDataString(Navigation.Uri)}");
                return;
            }

            dispatcher.Dispatch(new StartAppAction());

            return;
        }
    }
```

When the browser does a hard reload the StartAppAction does not get dispatched. When the browser does a soft reload this works fine.

I can reproduce this behaviour in Edge, Chrome & Firefox

**Comment by mrpmorris** [comment]
Is it because I'm those cases user.Identity.IsAuthenticated is returning false?

**Comment by HannahKiekens** [comment]
No, in that case the user gets redirected to "authentication/login" as the code says. 
IT looks like the Dispatch doesnt happen and the code functions normaly

**I expect this behaviour:**
when the app starts, if the user isnt authenticated, I redirect them to a OIDC provider.
The app returns to "returnUrl" and starts a second time with an authenticated user

What I am seeing:
The app returns with an authenticated user. "dispatcher.Dispatch(new StartAppAction());" never gets called. The app continues to work with authentication as expected.
When I hit F5 to softload the app again, it does work


And I cant attach a debugger at this early point in wasm startup as VS doesnt support it

**Comment by HannahKiekens** [comment]
Is it possible Fluxor Dispatches StoreInitializedAction **before**  AuthenticationStateProvider is able to run ?
And is it possible the startup order of these middlewares is different depending on a soft or hard reload ??

**Comment by mrpmorris** [comment]
It initializes when first rendered. But then Blazor will async call code to check with. So the initialize will happen first. 

You could try removing StoreInitializer from App.Razor and in your AuthorizeView component put one inside Authorized and one inside NotAuthorized.

Does that work?

**Comment by HannahKiekens** [comment]
> Have an effect that listens for `StoreInitializedAction`, then uses `AuthenticationStateProvider` to asynchronously get the user info. Then you can dispatch an action according to whether the user is signed in or not.

Is this different then the code I showed in the issue?


It behaves as if StoreInitializedAction can be dispatched before my Effect is loaded/registered???
My state/features are in a separate different assembly
``` C#
            services.AddFluxor(options =>
            {
                options.ScanAssemblies(typeof(Scoops.Cms.Application.Dummy).Assembly);
                options.UseReduxDevTools();
            });
```

**Comment by mrpmorris** [comment]
Sorry, you are right. 

Looks like it might be a blazor bug perhaps? StoreInitializedAction isn't dispatched until after the first render, and you should be able to access to current user before you render. I wonder if this is as-designed?

Try taking out the StoreInitializer component.  Then put one in your Authorized view instead.  Also put one in the Unauthorized view if needed.

**Comment by HannahKiekens** [comment]
I ended up refactoring my code to only initialize the store for Authenticated users. Pulling this behaviour out of the flux pattern
This avoids the observed "weirdness" during startup
