### ISSUE TITLE
Redux Dev Tools stop working with RenderFragments

### ISSUE THREAD

**Issue by AllanFerencz** [mrpmorris/Fluxor#175]
I've been working on a modal component. It basically displays any render fragment passed in and displays them

ModalContainer.razer

```
@using Fluxor

@inherits Fluxor.Blazor.Web.Components.FluxorComponent
@inject IState<Store.ModalState> ModalState

@ModalState.Value.Modal
```
<br />
I use it to trigger different modals.

Example of a cancel modal.
<br />
``` C#
private void OpenCancelOrderModal()
{
    Dispatcher.Dispatch(new Store.Features.Modal.Actions.OpenModal(OrderState.Value.Order.PackageId, cancelOrderModal));
}

static readonly RenderFragment cancelOrderModal = __builder =>
{
    <CancelOrderModal />
};
```
<br />
It works as expected but the Redux debugger stops keeping track of any action.
I'm pretty sure it has to do with this modal state
<br />

``` C# 
public bool IsOpen { get; set; }
public RenderFragment Modal { get; set; }

public ModalState(bool isLoading, string currentErrorMessage, bool isOpen, RenderFragment modal) : base(isLoading, currentErrorMessage)
{
    IsOpen = isOpen;
    Modal = modal;
}
``` 

The main thing being the RenderFragment. Is this not a recommended practice?

**Comment by mrpmorris** [comment]
Your dependencies won't be injected when the constructor runs. Move the Dispatch to OnInitialized

**Comment by mrpmorris** [comment]
Can you provide a repro for me to look at?

**Comment by mrpmorris** [comment]
I'll need a repro for this, or I won't be able to investigate.

**Comment by abspro** [comment]
@mrpmorris Have you used a renderfragment with this library and had the dev tools still record actions?

**Comment by abspro** [comment]
In my experience, adding a RenderFragment as an argument to an action and dispatching it, or adding a fluxcomponent aka `this` as an argument to an action will cause the extension to stop working.  I ended up pulling these parts out of my flux store and just did them the normal blazor way.  

For context, I was working with a wizard component which had it's steps added as render fragments.  Each wizard step would register itself with the parent wizard component on initialization by passing itself as an argument to a register action.  When this happens it breaks the browser extension and it will no longer show any further actions.

I'll get a repo for you later today.

**Comment by afouadr** [comment]
IMHO: RenderFragments are part of View machinery not to be confused with "immutable state" for which we are using Fluxor in first place. Its better to always reason about what comprises immutable state. Keep you store classes/implementation from referencing UI types.
HTH

**Comment by mrpmorris** [comment]
Render fragments are tied to the component that created them. They shouldn't be dispatched in actions.
