### ISSUE TITLE
State slice

### ISSUE THREAD

**Issue by KevinBurton** [mrpmorris/Fluxor#177]
I am very new to Fluxor but looking at the tutorials it seems that one is always working with a single global state. So for example if I have GlobalState that contains CounterState and WeatherState., if I update CounterState then it is equivalent to updating GlobalState. There doesn't seem to be a way to subscribe to just CounterState or conversely subscribe to GlobalState and be notified when changes to CounterState or WeatherState occur. These are on the subscription side but I have the same questions for modifying 'slices' of state.

**Comment by mrpmorris** [comment]
Create one Fearure<TState> descendant for each piece of state and it will get picked up
