### ISSUE TITLE
Suggestion: Use records for states and actions

### ISSUE THREAD

**Issue by TheBoss3433** [mrpmorris/Fluxor#179]
Very good library, I've been using it the past few days and had a suggestion. It does not require any changes to codebase but mainly to documentation as it works out of the box.

Creating State using C# 9.0 records instead of class makes the state trully immutable and also reduces amount of code required in reducers when utilizing the state with {prop = new value}. For actions, it reduces the amount of code needed to create them.

Ex: 

State declaration:
```C#
public record CounterState(int CounterCount)
```
Actions
```C#
public record IncrementCounterAction();
```
Reducers
```C#
        [ReducerMethod]
	public static CounterState ReduceIncrementCounterAction(CounterState state, IncrementCounterAction action) =>
		state with { CounterCount = state.CounterCount + 1}
```

The advantage for this format is not as clear with small state but as it gets bigger it's easier to see exactly what is being changed in with each action....

```C#
public record ExampleState(int Ex, ICollection<Something> Somethings, string Tittle);

public record UpdateExampleTittleAction(string Tittle);

[ReducerMethod]
public static ExampleState ReduceUpdateExampleTittleAction(ExampleState state, UpdateExampleTittleAction action) =>
            state with {Tittle = action.Tittle}
```

Sorry for bad english

**Comment by mrpmorris** [comment]
The only place the library itself has state/actions is the routing middleware. I can't use records there without dropping support for net 2.1

**Comment by Pjotrtje** [comment]
It is a bit hacky, but you could do this: 
https://blog.ndepend.com/using-c9-record-and-init-property-in-your-net-framework-4-x-net-standard-and-net-core-projects/

**Comment by mrpmorris** [comment]
I don't think there is a benefit. One action class and one state class, neither of which change.

**Comment by tdashworth** [comment]
I have chosen to use records for all my actions and states. There is far less code and works really well for me. 

For the package, I think it should be an opt-on like I've chosen to use it. There could be some documentation to educated about them but you don't want to drop net 2.1 support.

**Comment by mrpmorris** [comment]
You can use records in your own apps, there is nothing I have to do to support them
