### ISSUE TITLE
state is always one step behind after dispatch.

### ISSUE THREAD

**Issue by CD1010** [mrpmorris/Fluxor#18]
In the following code, when i click the submit button, it toggles between 2 states: 
Visible: T F F  
and 
Visible T T T 

The initial state in the store is T F T.  

This causes Links for Second and Third steps to toggle between active and inactive.

Observations: 
1)  If i hit the button, nothing changes, but if i navigate away from page and come back, i see the updated state.  
2) If i stay on the page and hit the button multiple times, it toggles, but is always showing the previous state.
3) If i refresh the site with the browser, whatever state i had is reset to the initial state.

So why am i seeing condition 1 and 2 and why does refresh lose the whole session state in item 3 above?
 
@using Fluxor;
@using BlazorWizard.Store;
@using Blazorise; 
@inject IState<WizardState> state
@page "/wizarddemo"
@inject IDispatcher dispatcher
@inherits Fluxor.Blazor.Web.Components.FluxorComponent

<Wizard Id="DemoWizard">

    <WizardStep Name="First" @bind-Enabled="@state.Value.States[0].Visible">
        <div class="row">
            <FirstStep></FirstStep>
        </div>
    </WizardStep>

    <WizardStep Name="Second Step" @bind-Enabled="@state.Value.States[1].Visible">
        <div class="row">
            <p>Wow, you've reached the second step!</p>
        </div>
    </WizardStep>
    <WizardStep Name="Final Step" @bind-Enabled="@state.Value.States[2].Visible">
        <div class="row">
            <p>The final step has been reached. Thank you \o/</p>
        </div>
    </WizardStep>
</Wizard>
<Blazorise.Button Class="btn-lg btn-primary" Clicked="OnSubmit">Submit</Blazorise.Button>

@code {
    Wizard TheWizard { get; set; }

    void OnSubmit()
    {
        if (state.Value.States[1].Visible == false)
        {
            dispatcher.Dispatch(new BlazorWizard.Store.Wizard.WizardAllOnAction());
            System.Diagnostics.Debug.WriteLine("All On");
        }
        else
        {
            dispatcher.Dispatch(new BlazorWizard.Store.Wizard.WizardFirstOnAction());
            System.Diagnostics.Debug.WriteLine("First ON");
        }
        StateHasChanged();
        ShowStates();
    }

    protected override void OnInitialized()
    {

        //   dispatcher.Dispatch(new BlazorWizard.Store.Wizard.WizardFirstOnAction());
        // System.Diagnostics.Debug.WriteLine("First on Init");
        //StateHasChanged();
        base.OnInitialized();
    }
    protected override void OnParametersSet()
    {
        //state.StateChanged += (o, ws) =>
        //{
        //    StateHasChanged();
        //};
        base.OnParametersSet();

    }
    void ShowStates()
    {
        System.Diagnostics.Debug.WriteLine("States");
        foreach (var item in state.Value.States)
        {
            System.Diagnostics.Debug.WriteLine(item.Visible);
        }
    }
}

**Comment by CD1010** [comment]
Condition 3) above is reproducable in Fluxor counter and blazor-fluxor samples.  So fluxor does not preseve state between refreshes of browser?  Is that by design?  I thought it is analogous to session state.

**Comment by mrpmorris** [comment]
Re #3. That's the way Blazor works. If you do a physical refresh then it creates a new connection to the server and is equivalent to creating a new state.

As for your other problems, it's difficult for me to see what is going on. One thing that struck me as being a bit odd is that you are using two-way binding against what should be read-only state.

Change `@bind-Enabled="@state.Value.States[0].Visible"` to `Enabled=@state.Value.States[0].Visible` and see if that makes any difference.

**Comment by mrpmorris** [comment]
As I've not heard back I am going to assume this was related to mutable state and two-way binding. If this is not the case then please get back to me and I'll reopen and try to help you to resolve your problem.

**Comment by CD1010** [comment]
Yes, the @bind-enabled is just me thrashing around for  a solution.   I just don't get why that click handler does n't refresh the page while you are on it and after the dispatch.  ( Forget about manual refresh for a moment ).
I can just hit the button, go back to another page and come back and THEN the state is updated.


    On Friday, April 17, 2020, 05:06:19 PM EDT, Peter Morris <notifications@github.com> wrote:  
 
 


Re #3. That's the way Blazor works. If you do a physical refresh then it creates a new connection to the server and is equivalent to creating a new state.

As for your other problems, it's difficult for me to see what is going on. One thing that struck me as being a bit odd is that you are using two-way binding against what should be read-only state.

Change @bind-Enabled="@state.Value.States[0].Visible" to Enabled=@state.Value.States[0].Visible and see if that makes any difference.

**Comment by CD1010** [comment]
https://github.com/CD1010/BlazorWizard/tree/StepActivations  This is the code i am referring to in this issue.    
I now understand the limitations in Blazor regarding item 3 above.  I don't much like that, however.  I am thinking i need to store state in localstorage also, so it survives refreshes.  Something like good old Session behavior is what i am looking for.

As for 1 and 2,  I still see that behavior no matter what i try.  Is that an issue in fluxor or something i am doing wrong?   Thanks.  Try hitting "Toggle State" button and you will see state rendered is always one button click behind.

**Comment by mrpmorris** [comment]
I see it. I will investigate. Thanks!

**Comment by mrpmorris** [comment]
It is because you are iterating over the steps and showing Step.Enabled, and then after that you are displaying the steps (which will bind the properties of the steps).

**Comment by mrpmorris** [comment]
```
@foreach (var item in Steps.Select((x, i) => new {  Step = x, Index = i}))
{
	item.Step.SetEnabled(state.Value.States[item.Index].Visible);
	... your code here...
}
```
