### ISSUE TITLE
State updates consistently not taking effect in edge use case

### ISSUE THREAD

**Issue by tdashworth** [mrpmorris/Fluxor#181]
I have noticed in one edge case that state updates aren't being applied. By that I mean:
- I don't see the UI update
- I don't see a resulting action in the Chrome Extension  
- I DO hit a breakpoint in the reducer method

I am building a game with SignalR and as events/action take place, they are sent to an ASP.NET (.NET 5) server that broadcasts the event back to all players within a game (SignalR group). This message IS being received by the browser client. A player can join the game at any point and they will sit within a lobby until a new round begins. This does not change the fact that it receives SignalR messages. 

I would like these "in lobby" players to still watch the game and therefore react to the events taking place. As mentioned, I see the SignalR message come in and dispatch an event through Fluxor and a breakpoint is hit within the reducer method for said action. The result is no state change (although for the "playing" players in works fine). 

What could be the cause of this? 

The repo is here: https://github.com/tdashworth/cards-against-whatever (please ask if you need access since it's currently, private)

**Comment by mrpmorris** [comment]
I tried running the app but it wants me to browse for a card-set and I cannot see any in the repo.

**Comment by tdashworth** [comment]
@mrpmorris I have added a sample set made of lorem lipsum (I don't want to share the actual cards for copyright purposes). https://github.com/tdashworth/cards-against-whatever/blob/master/SampleCardDeck.csv

You need at least two players to start a round so just launch a second tab and join with the generated game code. 

My test case is: 
1. Player 1: Create and join game
2. Player 2: Join game
3. Player 2: Start round
4. Player 3: Join game (they will stay in the lobby but they should see the players, question, and round details)
5. Player 2: Select one or two cards (depends on the question) and play those
6. ASSERT: Players 1, 2 & 3 should see the played cards of Player 2 after a second delay and show the player statuses:
- Player 1 as "Hummm, who's is the best..."
- Player 2 as "I'm done!"
- Player 3 as "Chilling in the lobby"

FAIL: Player 1 and 2 are fine. Player 3 gets no UI update.

Thank you for taking a look.

**Comment by tdashworth** [comment]
It was of course an error in my application 😑 that silently failed.

**Comment by mrpmorris** [comment]
The StoreInitializer component has a UnhandledException parameter you can use, if that helps?
