### ISSUE TITLE
Question: How do you suggest to solve persisting state 

### ISSUE THREAD

**Issue by anddrzejb** [mrpmorris/Fluxor#183]
Obligatory praise - great library! Thanks for all the work!

I am looking for best solution on how to implement persisting state between reloads. Now, if a user presses F5, the state is lost. 

What I did is going against what was written in the tutorial, but at this stage I do not know how to do it otherwise and I am looking for suggestions.

My current solution involves creating 2 new base classes on top of `Fluxor`:
1. `RestoringFeature<TState>: Feature<TState>` . In the constructor it receives the service that is responsible for getting persisted state, and loads it the `State` property with either retrieved state or initial state (call to `GetInitialState()`). A very basic code:
```csharp
public abstract class RestoringFeature<TState> : Feature<TState> 
    {
        private readonly string _identifier;
    
        public RestoringFeature(IStatePreserver refresh)
        {
            _identifier = $"{GetName()}";
            State = refresh.Get(Identifier, GetInitialState());
        }

        protected virtual string Identifier => _identifier;

        public override string GetName() => base.GetStateType().FullName ?? base.GetStateType().Name;
    }
```

2. `PreservingReducer<TState, TAction>: Reducer<TState, TAction>`. In the constructor it receives the service that is responsible for setting persisted state. It also overrides the `Reduce` method and creates an abstract method `ReduceWithPreserve` (arguments and return are identical to `Reduce`).
```csharp
    public abstract class PreservingReducer<TState, TAction> : Reducer<TState, TAction> 
    {
        protected readonly IStatePreserver Refresh;
        private readonly string _identifier;
        public PreservingReducer(IStatePreserver refresh)
        {
            Refresh = refresh;
            _identifier = $"{typeof(TState).FullName ?? typeof(TState).Name}";
        }

        protected abstract TState ReduceWithPreserve(TState state, TAction action);

        public override TState Reduce(TState state, TAction action)
        {
            var newState = ReduceWithPreserve(state, action);
            Preserve(newState);
            return newState;
        }

        protected virtual string Identifier => _identifier;

        public virtual void Preserve(TState state) => Refresh.Set(Identifier, state);
    }
```
So my typical `Feature` looks like this:
```csharp
   public class ExampleFeatureState : RestoringFeature<ExampleState>
    {
        public ExampleFeatureState(IStatePreserver refresh) : base(refresh) {}

        protected override ExampleState GetInitialState() => new ExampleState
        {            
             ExampleProperty = ""
        };
   }
```
and typical reducer looks like this:
```csharp
    public class ExampleReducer : PreservingReducer<ExampleState, ExampleAction>
    {
        public ExampleReducer(IStatePreserver refresh) : base(refresh) { }

        protected override ExampleState ReduceWithPreserve(ExampleState state, ExampleAction action)
        {
            return state with
            {
                 ExampleProperty = "reduced"
            };
        }
    }
```

My beef with this is that I basically cannot really use here recommended static reducer approach, because I am injecting the `IStatePreserver` service. But I have to if I want to preserve any change to the state... Why does documentation "strongly recommends" static approach and what are the dangers of using my approach? I am also open to any suggestion how I could improve my design. 
My other attempts were involving using `Effects` and using `[ReduceMethod]` on an instance and injecting `IStatePreserver` in constructor, but this introduces so much additional ceremony and I (as well as anyone in my team) need to remember about calling `Preserve` method in every `Reducer` once the new state is ready to be returned....

**Comment by mrpmorris** [comment]
I'd write middleware. Before an action is dispatched, grab a dictionary of all states' values keyed by feature name...

https://github.com/mrpmorris/Fluxor/blob/0fb6404e297838aa66054c2bcdea99cb8c0f8495/Source/Fluxor.Blazor.Web.ReduxDevTools/ReduxDevToolsMiddleware.cs#L67

After an action is dispatched check which states have changed (the value will be a new object instance) and serialize + store each one that had changed. 

In InitializeAsync read the values and restore the states https://github.com/mrpmorris/Fluxor/blob/0fb6404e297838aa66054c2bcdea99cb8c0f8495/Source/Fluxor.Blazor.Web.ReduxDevTools/ReduxDevToolsMiddleware.cs#L90

This might help
https://github.com/mrpmorris/Fluxor/blob/master/Source/Fluxor/Middleware.cs

Put your middleware in its own namespace.  Features/Effects in the same namespace as middleware are considered part of the middleware so won't be auto discovered if you haven't used AddMiddleware to add it.

**Comment by anddrzejb** [comment]
Thanks for such a quick response! Sorry it took me so long to react - I had some fires to put out.

I looked at your suggested solution and I have a question, as I am not sure if I understand correctly. You suggested to basically scan the whole store in the `AfterDispatch` in search of which state had changed? And you wrote that the changed value will be a new object instance. So, is there any other way for checking this except `ReferenceEquals` method? Or is there any method within Fluxor that I can use to get states changed after dispatch?

**Comment by mrpmorris** [comment]
You could subscribe to the states' StateChanged event and persist from there.

**Comment by anddrzejb** [comment]
I'm sorry, I am still trying to understand the suggested approach.
So, I can subscribe to StateChanged event. As far as I can see it, this should either happen from
1.  Feature - probably in the constructor. To avoid boilerplate, it still seems to me that creating a new base class (as I did in the original post) would be my best bet.
2. Middleware - scan the store to figure out new incoming state, so the event handler can be added. That includes additional logic to find out which states are already subscribed to.
3. ??
