### ISSUE TITLE
Dispatcher in DelegatingHandler

### ISSUE THREAD

**Issue by PeterKottas** [mrpmorris/Fluxor#185]
Hi, I have created a relatively simple setup. I want to automatically recognize loading state of Http requests.
The logic is:

Create HttpClient MessageHandler (DelegatingHandler) that uses dispatcher to dispatch simple Start and Stop actions.
The reducer then takes these actions and figures out if all requests that started have indeed finished.
Here is the code:

```
public class LoadingMessageHandler : DelegatingHandler
    {
        private readonly ILogger<LoadingMessageHandler> looger;
        private readonly IServiceProvider provider;

        public LoadingMessageHandler(ILogger<LoadingMessageHandler> looger, IServiceProvider provider)
        {
            this.looger = looger;
            this.provider = provider;
        }

        protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            var dispatcher = provider.GetService<IDispatcher>();
            try
            {
                looger.LogError("Starting");
                dispatcher.Dispatch(new StartLoading());
                var resp = await base.SendAsync(request, cancellationToken);
                return resp;
            }
            catch (Exception)
            {
                throw;
            }
            finally
            {
                looger.LogError("Finished");
                dispatcher.Dispatch(new FinishLoading());
            }
        }
    }
```

The logging that I put there verifies that the dispatcher is being called.

Next I've create a very straight forward store:
```
public class LoadingState
    {
        public bool IsLoading { get { return Count > 0; } }

        public int Count { get; init; }
    }
```
Reducers:
```
public class Reducers
    {
        [ReducerMethod]
        public static LoadingState ReduceStartLoadingAction(LoadingState state, StartLoading action)
        {
            return new LoadingState()
            {
                Count = state.Count + 1,
            };
        }

        [ReducerMethod]
        public static LoadingState ReduceFinishLoadingAction(LoadingState state, FinishLoading action)
        {
            return new LoadingState()
            {
                Count = state.Count - 1,
            };
        }
    }
```
Feature:
```
public class Feature : Feature<LoadingState>
    {
        public override string GetName() => "Loading";

        protected override LoadingState GetInitialState() =>
            new LoadingState()
            {
                Count = 0
            };
    }
```
Actions (just for completeness sake):
```
public class StartLoading
    {
    }

    public class FinishLoading
    {
    }
```
The problem is the actions are not handled by fluxor pipeline.
I suspect this can have something to do with the DI scopes. I tried various combinations of scoping (singleton, scoped and transient) but nothing helped.

This is the code I use to register this stuff:
```
builder.Services.AddHttpClient(HttpClientConstants.ChatBotApiHttpClient, client => client.BaseAddress = new Uri(builder.HostEnvironment.BaseAddress))
                .AddHttpMessageHandler<BaseAddressAuthorizationMessageHandler>()
                .AddHttpMessageHandler<LoadingMessageHandler>();

            builder.Services.AddScoped<LoadingMessageHandler>();
            builder.Services.AddScoped(sp => sp.GetRequiredService<IHttpClientFactory>().CreateClient(HttpClientConstants.ChatBotApiHttpClient));
var currentAssembly = typeof(Program).Assembly;
            builder.Services.AddFluxor(options =>
            {
                var o = options.ScanAssemblies(currentAssembly);
                if (builder.HostEnvironment.IsDevelopment())
                {
                    o.UseReduxDevTools();
                }
            });
```

I do use Fluxor in other places in the app where it works. I also use Redux Dev Tools where I can see all actions except for these. Any ideas?

**Comment by PeterKottas** [comment]
It is my understanding that MessageHandlers are only created once for performance reasons. The best I could figure out was this:
```
public class LoadingMessageHandler : DelegatingHandler
    {
        private readonly ILogger<LoadingMessageHandler> looger;
        private readonly IServiceProvider provider;

        public LoadingMessageHandler(ILogger<LoadingMessageHandler> looger, IServiceProvider provider)
        {
            this.looger = looger;
            this.provider = provider;
        }

        protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            using (var scope = provider.CreateScope())
            {
                var dispatcher = scope.ServiceProvider.GetService<IDispatcher>();
                try
                {
                    looger.LogError("Starting");
                    dispatcher.Dispatch(new StartLoading());
                    var resp = await base.SendAsync(request, cancellationToken);
                    return resp;
                }
                catch (Exception)
                {
                    throw;
                }
                finally
                {
                    looger.LogError("Finished");
                    dispatcher.Dispatch(new FinishLoading());
                }
            }
        }
    }
```
But unfortunately, it still doesn't work.

I have a feeling that this will have something to do with the way Fluxor registers (and initializes) its components and with the nature of the MessageHandler lifecycle.

As a side note, when I debug, the dispatcher indeed shows the store is not initialized. It also lacks any registrations. I wonder if it's somehow still injecting the uninitialized instance.

**Comment by mrpmorris** [comment]
Fluxor is registered as Scoped, so that multiple users can have their own state (e.g. in a Blazor Server app) - but your handler will be created as a singleton.

So in every case, you get the wrong scope and therefore the wrong store.

You could create a scoped service which you use to issue Http requests

**Comment by PeterKottas** [comment]
I see what you mean, but shouldn't this:
```
using (var scope = provider.CreateScope())
            {
                var dispatcher = scope.ServiceProvider.GetService<IDispatcher>();
```
Force the dispatcher to be "up to date"? Or is it simply just returning some random new scope that is different from the one blazor is running on?

I wonder if it would be a good idea to introduce a few more complex examples. Stuff-like resource fetching with some shared logic for loading is IMHO pretty standard. But I think people might have to reinvent a few key aspects over and over again when working with blazor.

E.g. : Right now, I fetch resources like this:
```
public class FetchAllChatBotsEffect : Effect<FetchAllChatBots>
    {
        private readonly ApiClient client;

        public FetchAllChatBotsEffect(ApiClient client)
        {
            this.client = client;
        }

        public override async Task HandleAsync(FetchAllChatBots action, IDispatcher dispatcher)
        {
            dispatcher.Dispatch(new StartLoading());
            try
            {
                dispatcher.Dispatch(new SaveAllChatBotsAction(FetchingStatusEnum.Loading));
                var resp = await client.GetChatBots();
                dispatcher.Dispatch(new SaveAllChatBotsAction(FetchingStatusEnum.Loaded, resp.ChatBots.Items));
            }
            catch (System.Exception)
            {
                dispatcher.Dispatch(new SaveAllChatBotsAction(FetchingStatusEnum.Error));
            }
            finally
            {
                dispatcher.Dispatch(new FinishLoading());
            }
        }
    }
```
Notice the start and finish loading actions being triggered manually. Not good ... repetition, boiler code etc. So naturally, I tried to move these calls into the ApiClient. But that won't work because if the ApiClient depends on the IDispatcher, I cannot use it inside the effect. Also thb, the client should not know about the dispatcher, it's not its job to know that. So I've created this extension method:

```
public static async Task WithLoading(this IDispatcher dispatcher, Func<Task> action)
        {
            dispatcher.Dispatch(new StartLoading());
            try
            {
                await action();
            }
            catch (System.Exception)
            {
                throw;
            }
            finally
            {
                dispatcher.Dispatch(new FinishLoading());
            }
        }
```
Which changes the previous method into
```
await dispatcher.WithLoading(async () =>
            {
                try
                {
                    var resp = await client.GetChatBots();
                    dispatcher.Dispatch(new SaveAllChatBotsAction(FetchingStatusEnum.Loaded, resp.ChatBots.Items));
                }
                catch (System.Exception)
                {
                    dispatcher.Dispatch(new SaveAllChatBotsAction(FetchingStatusEnum.Error));
                }
            });
```
Much cleaner IMHO, but still some extra code. Is this it? Frankly, I don't know. It keeps the component very clean and testable as I simply trigger action and don't care anymore. Just wait for the state to change. But there might be a better way. How do you do this? I used to have this done very neatly in react/redux but the MessageHandler scoping is making this difficult. Naturally, there are plenty of approaches but did something prove to be extra useful/powerful?

**Comment by mrpmorris** [comment]
> using (var scope = provider.CreateScope())

That creates an entirely new scope. CreateScope is like adding a child to a node in a tree.

Instead of StartLoading and FinishLoading actions, you can have a reducer method on your Loading State for each action that affects it.

```
[ReducerMethod(typeof(SaveAllChatBotsAction)]
public static YourState ReduceSaveAllChatBotsAction(YourState state) =>
    state with { LoadingCount = state.LoadingCount + 1 },

[ReducerMethod(typeof(SaveAllChatBotsResultAction)]
public static YourState ReduceSaveAllChatBotsAction(YourState state) =>
    state with { LoadingCount = state.LoadingCount -1 1 },
```

// And other actions here that affect that state

By the way, I recommend splitting actions into Action/ResultAction so that you don't trigger Effects when not needed.

**Comment by PeterKottas** [comment]
I like that, although it might be difficult to spot a missing reducer for start/stop. With the extension method at least if you forget entirely, you won't get an unbalanced loading state. I'll see if I can come up with something really good. But yours or mine tbh are pretty good for now.

**Comment by mrpmorris** [comment]
I'd be more inclined to have a service for those calls, and each method in the service calls a common method for making the request.

**Comment by PeterKottas** [comment]
That would be an issue because the service would need the dispatcher and therefore it wouldn't work inside effect. To me, the effect is the perfect place to handle fetching stuff. Although I come from redux and maybe I just have to accept the fact that here it's different. 

To be fair, it seems much less of a deal to do long-running async stuff on components in blazor as opposed to react, at least for now.

Maybe having an APIClient and another service, let's call it UIClient would work best. Then you could use APIClient (clean with no dispatcher) insider effects (if need be) and use the UIClient for UI-specific tasks that update the state. E.g. loading, state saving, and what have you.
