### ISSUE TITLE
ServiceCollectionExtensions namespace and file folder mismatch

### ISSUE THREAD

**Issue by sanderobdeijn** [mrpmorris/Fluxor#186]
I was looking for the ServiceCollectionExtensions class.
According to the code it is in the fluxor namespace so I expected the file to be in the /Source/Fluxor folder but it was in the /Source/Fluxor/DependencyInjection folder.
It probally should be the one or the other.

**Comment by mrpmorris** [comment]
I like it how it is :)

Did you know you can press CTRL+(comma) and then start to type the name?
