### ISSUE TITLE
Option to prevent scanning the middleware assembly when adding middleware

### ISSUE THREAD

**Issue by TheBoss3433** [mrpmorris/Fluxor#189]
https://github.com/mrpmorris/Fluxor/blob/0fb6404e297838aa66054c2bcdea99cb8c0f8495/Source/Fluxor/DependencyInjection/Options.cs#L65-L72

Any particular reason why this is the case?

**Comment by mrpmorris** [comment]
Why what is the case?

**Comment by TheBoss3433** [comment]
Why does it scan the middleware namespace? I believe this causes a bug when the middleware is defined in assembly but not actually used.

I will create a repo to show you

**Comment by mrpmorris** [comment]
It won't scan any namespace that has middleware in it unless you use AddMiddleware

It's by design,  so effects/reducers that accompany the middleware aren't loaded of it isn't added
