### ISSUE TITLE
routing middleware future enhancements? target?

### ISSUE THREAD

**Issue by rlasjunies** [mrpmorris/Fluxor#195]
Hi Peter,

 In my "personal" application I manage any activity via "action". Even for the navigation, navigateTo ... using GoAction() provided by your routing middleware
 Now, I need to manage a navigation back.

Do you plan @routing to stay a middleware (observe NavigationManager)? 
or is it ok to add new actions in the middleware ? ... in that I may propose you my future implementation. 
Otherwise, I will create a feature to wrap the navigation manager.

**Comment by mrpmorris** [comment]
If you want to contribute additions to the routing middleware then I need details

**Comment by rlasjunies** [comment]
The proposal would be to have an history the urls navigated by the application and one new action 'GoBackAction' to navigate back to the previous url.

Each time the app navigated to an Url, the url is pushed in a stack.
The GoBackAction will pop the last url and navigate to the poped url.

**Comment by rlasjunies** [comment]
ok, no prob, 
I will create a fluxor feature to handle the behavior expected
