### ISSUE TITLE
Additional Features in Fluxor Scope

### ISSUE THREAD

**Issue by MutatePat** [mrpmorris/Fluxor#196]
Hi all,

Is it in the scope of Fluxor to support undo/redo functionality, as a well as, exporting the log( shown in Redux Dev Tools) using code?

I am looking to implement undo/redo myself in my own project - however if it is in the scope of Fluxor, then this functionality best belongs in this repo or a subpackage( i.e Fluxor.Undo) 

Additionally, exporting the action log with state history would be useful for client usage data, as well as to assist with support functions. Not sure if this possible however without completely replicating the Redux Dev Tools functionality.

**Comment by mrpmorris** [comment]
Hi

You'll need to write your own undo/redo. I think the idea is to have your reducer not only reduce state that is affected by the command, but also create a command that can be dispatched to undo it and put it in a stack in the state.
