### ISSUE TITLE
Unable to catch Fluxor exception

### ISSUE THREAD

**Issue by AlexTeixeira** [mrpmorris/Fluxor#201]
Hello, 

I'm implementing the Global Error Handler from microsoft documentation, but I face an issue when It come to the Fluxor Exception

![image](https://user-images.githubusercontent.com/6555080/125916660-717c4c82-946c-4aea-ba0a-0ef2fb4a1217.png)

I set my _try catch_ in the **OnAfterRenderAsync**, but the exception is not catch

```
    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        try
        {
            await base.OnAfterRenderAsync(firstRender);
        }
        catch (Exception e)
        {
            Error.ProcessError(e);
        }
    }
```

Can you please, add a sample of code to manage Fluxor exceptions.

**Comment by mrpmorris** [comment]
Does setting UnhandledException on `StoreInitializer` do what you need?

https://github.com/mrpmorris/Fluxor/blob/master/Source/Fluxor.Blazor.Web/StoreInitializer.cs#L18

**Comment by AlexTeixeira** [comment]
Hi,

Seems to be the setting I need. I do not test it yet, but just by reading the code I think this issue can closed :)
