### ISSUE TITLE
[Question] best practice for using multiple stores in a page

### ISSUE THREAD

**Issue by ThaRaven403** [mrpmorris/Fluxor#202]
Hi,

I'd like to know what would be your recommended best practice for handling the usage of multiple stores on a page.
For example, two different stores will have an action dispatched when arriving on the page, triggering a new state with IsLoading=true for both. Should we just check both flags? 

Another related question would be the best pattern for having stores when you authenticate. Should a layout for authenticated pages dispatch the necessary actions, or would it be better someplace else?

Thanks in advance!

**Comment by mrpmorris** [comment]
You shouldn't have two stores. If you need to separate tasks or state then you need multiple features within a single store.

As for auth. I'd need to know how you are doing it. Is it a page that redirects to your app, or is it a page within your app? The general advice is to have an effect go and do the auth, and then dispatch an action based on the result.

**Comment by ThaRaven403** [comment]
Yeah sorry about the wording, but it's indeed multiple feature/state. So with that in mind, say I need both the CounterFeature and WeatherForecastFeature in a page, do you simply check both are ready or should something else manage the readiness of the page ?

As for the auth, I actually didn't think about it since we didn't have actions/effects setup for this yet (re-used code from a previous project), but yeah that's the change I'll have to do for this.

**Comment by mrpmorris** [comment]
You can have one per state, and in your ui check a.IsReady && b.IsReady
