### ISSUE TITLE
Proposal: support overriding action name displayed in ReduxDevTools

### ISSUE THREAD

**Issue by hillin** [mrpmorris/Fluxor#205]
Currently [action names are generated from the action type name and its namespace](https://github.com/mrpmorris/Fluxor/blob/ed06a656ce48b06ff584d82462b521bb58e8db20/Source/Fluxor.Blazor.Web.ReduxDevTools/ActionInfo.cs#L17). While this is good enough for most use cases, it's not friendly for generic actions, e.g.:
```c#
public record LoadSuccessAction<TPayload>(TPayload Data);
```

The proposal is to add an `IOverrideActionName` interface (or whatever name it is), so the action could specify its own name:
```c#
public record LoadSuccessAction<TPayload>(TPayload Data, string ActionName) : IOverrideActionName
{
    string IOverrideActionName.Name => this.ActionName;
}
```

This is important to for use cases like the `AsyncLoadEffect` mentioned in https://github.com/mrpmorris/Fluxor/issues/203#issuecomment-902587977.

**Comment by mrpmorris** [comment]
I assume it shows a weird auto-generated name? I could fix it to show `LoadSuccessAction<Person>` etc. Would you prefer that?

**Comment by hillin** [comment]
Yes currently it generates a name like ``LoadSuccessAction`1``. I think `LoadSuccessAction<Person>` is good enough for this case.
