### ISSUE TITLE
Fluxor (Blazor) - Layout/Shared components

### ISSUE THREAD

**Issue by sianmace** [mrpmorris/Fluxor#206]
I have made a fluxor demo and have tried the todo examples and counter examples to see how the states work.

This was great, until I tried to use a state in the Blazor layout or in a shared component - ie one without a route.

These values do not refresh until i click on a link to another route.

Am i missing something?

**Comment by mrpmorris** [comment]
Hi. 

Could you post a note explaining why you closed this, in case it helps someone else in the future?

Thanks 👍

**Comment by sianmace** [comment]
Yeah sure, sorry.

I was being a stupid and missed adding  the FluxorLayout as the base class for the layout.
