### ISSUE TITLE
Problem when navigating pages inside effects

### ISSUE THREAD

**Issue by ABIOLI-COM** [mrpmorris/Fluxor#210]
I simplify my code here:

```
[EffectMethod]
...
{
    ...
    dispatcher.Dispatch(new EffectFinishedAction(...)); // dispatch (effect has finished the side effects, here just returning a new state, no side effects)
    navigationManager.NavigateTo("/"); // navigate
}
```

If I invert navigate and dispatch, the page doesn't change. I think that the correct sequence should be the inverted one, from a formal point of view, but since it doesn't work, I'm using this approach.
Any consideration?
Thank you in advance.
Andrea

**Comment by mrpmorris** [comment]
I'll close this for now. If you create a repro I will reopen it.
