### ISSUE TITLE
Remove Newtonsoft.Json dependency from ReduxDevTools

### ISSUE THREAD

**Issue by andrew-tevent** [mrpmorris/Fluxor#212]
It would be useful to remove this from the ReduxDevTools - otherwise it brings Newtonsoft into your Blazor app as a dependency!

Perhaps supply as separate package, e.g. `ReduxDevTools.NewtonsoftJson` ?

**Comment by mrpmorris** [comment]
It's only a debug tool, it shouldn't be deployed

**Comment by andrew-tevent** [comment]
Sure, but to have it in a project and not deploy requires a lot of jumping through hoops with csproj and compiler directives.

**Comment by mrpmorris** [comment]
Step 1: Edit your CSProj file and make sure the reference to Fluxor.Blazor.Web.ReduxDevTools is in its own ItemGroup with a condition on it, like so

```
	<ItemGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<PackageReference Include="Fluxor.Blazor.Web.ReduxDevTools" Version="4.0.0" />
	</ItemGroup>
```

Step 2: Put an `#if DEBUG` around opts.UseReduxTools, like so

```
			services.AddFluxor(opts =>
			{
				opts.ScanAssemblies(typeof(Program).Assembly);
#if DEBUG
				opts.UseReduxDevTools();
#endif
				opts.UseRouting();
			});
```

That's all there is to it.

**Comment by andrew-tevent** [comment]
Fair enough, yeah it's simpler than I thought! I wasn't aware you could have debug only NuGet packages. Thanks!
