### ISSUE TITLE
Redux-like Selectors

### ISSUE THREAD

**Issue by Crauzer** [mrpmorris/Fluxor#213]
I've recently started to use this library and it's fairly nice, however I'm confused as to how I'm supposed to get the state of other features in a different feature.

This is very easily done in Redux with selectors.

**Comment by mrpmorris** [comment]
Can you describe the scenario in more detail?

I'd like to know what your business requirement is, rather than how you are trying to solve it.

**Comment by Crauzer** [comment]
Well, I'm currently in the process of building up the architecture for the app.
I've been using WPF for a good time now and I'm transitioning to MAUI with Blazor, so I thought it would be great to try to use the Flux/Redux architecture in C#.

My main requirement is the ability to retrieve state from other features. So lets say I have a config feature. I want to be able to get its state in an effect without having to inject it into a component and passing down the data through actions.

**Comment by mrpmorris** [comment]
You can inject anything you wish via the constructor of an effect (except IStore or IDispatcher).

Does that help?

**Comment by Crauzer** [comment]
Thanks a lot!
This is exactly what I was trying to do 😃

**Comment by mrpmorris** [comment]
I think selectors are a code smell
