### ISSUE TITLE
Component base classes should be abstract

### ISSUE THREAD

**Issue by peterbozso** [mrpmorris/Fluxor#216]
Hi!

In my opinion, both `FluxorComponent` and `FluxorLayout` should be abstract base classes to better signify that they are like their parent classes (`ComponentBase` and `LayoutComponentBase` respectively), which means they should be used only as base classes and shouldn't be instantiated on their own.
To take this thought further, I think `FluxorComponent` should be renamed to `FluxorComponentBase` and `FluxorLayout` should be renamed to `FluxorLayoutComponentBase`. All in order to bring them closer to their parent classes' design.

If this is something worthy of implementing, then I am more than happy to contribute with a pull request!

Thanks,
Péter

**Comment by hellfirehd** [comment]
Breaking change, but I like it.

**Comment by mrpmorris** [comment]
Please do submit a PR for making them abstract. I don't want the breaking change of renaming though.

Thanks.
