### ISSUE TITLE
State not changing when using custom base class

### ISSUE THREAD

**Issue by psampaio** [mrpmorris/Fluxor#25]
I have a custom base class that implements basic parameter validation and awaits for the store to initialize (MyComponent < MyBaseClass < FluxorComponent). This base class has an `IState<State>` property (not in MyComponent) and the components are not being refreshed.

Maybe something in the StateSubscriber, when calling GetStateDelegatesForType is not detecting properties in base classes?

**Comment by mrpmorris** [comment]
I've not been able to reproduce this. I created a structure like so

1: CounterA : FluxorComponent
2: CounterB : CounterA
3: Counter : CounterB

And the counter updated. Can you provide something that reproduces this?

**Comment by psampaio** [comment]
I just re-tested and the root cause is that the IState property is private. If I change it to protected, it works. In my case, I keep it private and expose the relevant state properties as protected.

If this is the intended behavior, you can close this issue.

**Comment by mrpmorris** [comment]
It's not, I to use private state. I will have a look tomorrow. I'm due to do a release soon so hopefully I'll get to the bottom of this.

**Comment by mrpmorris** [comment]
Do you think you could send me a sample that reproduces this problem, please?

Thank you

**Comment by psampaio** [comment]
Here you go:
https://github.com/psampaio/fluxorsample

See BasePage.cs in the root. Basic workflow: Page1 and Page2 have a common underlying MyDomainObject that BasePage tries to load from the route Id. The OnAfterRenderAsync override is for when you go directly to the pages, waiting for the store initialization. If Id matches on of our objects, dispatch an action to select it, which changes the state and refreshes.

**Comment by mrpmorris** [comment]
Fixed in release 3.1.1, which should be available immediately.
