### ISSUE TITLE
Does Fluxor work with prerendering?

### ISSUE THREAD

**Issue by umunu** [mrpmorris/Fluxor#256]
I was using the library without prerendering and everything works as expected.
When I enabled prerendering the fluxor part wasn't working until the page is "loaded" through the wasm pipeline. 
There was the issue #146 which refer to the same problem and has a commit that closes it but I couldn't follow how this commit enables prerendering.
Is there somewhere in documentation that I am missing that describes how fluxor can be used along with prerendering? Or more importantly, can Fluxor be used with prerendering?

**Comment by mrpmorris** [comment]
I've not tried, but you might be able to manually initialize the store to make it work. You'd have to remove the StoreInitializer component from your view.

Please let me know the outcome.

**Comment by umunu** [comment]
The problem I see by manually initializing the store is the duplication of logic this involves. E.g. Lets say I load something in the OnInitializedAsync method by dispatching an action that is registered in an effect. If it succeeds a LoadSuccessAction is dispatched, if it fails a LoadFailAction is dispatched. With manual initialization this logic has to be written a second time without the dispatchers and actions.

**Comment by mrpmorris** [comment]
Ah yes, the actions are fire and forget, and that is a deliberate part of the pattern

**Comment by mrpmorris** [comment]
I'm closing this ticket. It doesn't support it and I don't think the pattern would allow it to.

**Comment by davicbaba** [comment]
i'm using fluxor in many projects and its awesome but now i need to implement pre-rendering to improve SEO. The only way is to remove flux from my project.

It would be awesome if fluxor support pre-rendering :(
