### ISSUE TITLE
Breaking change: Removed IState<TState> generic StateChanged event.

### ISSUE THREAD

**Issue by kjdamen** [mrpmorris/Fluxor#259]
Hi,

In release 5.0 the following has changed:
- StateChanged event has been Removed IState<TState> generic StateChanged event.
- Added IState<TState> alternative IStateSelector<TState, TValue> for selecting and subscribing to subsets of state. 

In my OnInitializedAsync I have included the following code. 

    _protected override async Task OnInitializedAsync()
    {
        // Register a state change to assign a newly created product id
        ProductState.StateChanged += (sender, state) =>
        {
            if (ProductValidationModel.Id == 0 && state.SelectedProduct != null)
            {
                ProductValidationModel.Id = state.SelectedProduct.Id;
                StateHasChanged();
            }
        };
    }_

Here I can no longer read the SelectedProduct property from state.
How can I apply this code in the 5.0 release?

Regards,
Kevin

**Comment by mrpmorris** [comment]
You'll need to typecast it.

What are you trying to achieve?

**Comment by kjdamen** [comment]
In the tutorial of the link below you will see a similar code in the component TodoDetail.razor.

[state-management-with-blazor-using-fluxor-part-2](https://betweentwobrackets.dev/posts/2020/07/state-management-with-blazor-using-fluxor-part-2/)

In the OnInitialized function the TodosState.StateChanged does not work anymore since version 5.0. State here is of type eventargs and it is not possible to typecast.

**Comment by mrpmorris** [comment]
The blog is now outdated. The correct way to obtain the new state is to inject `IState<T>` and read it from there.
