### ISSUE TITLE
Redux Dev Tools Trace Capability?

### ISSUE THREAD

**Issue by curt-w** [mrpmorris/Fluxor#262]
Is there support to enable the trace flag when using Redux Dev Tools? I cannot find any references to this.

I am having issue troubleshooting the origin of an action and believe the trace functionality would be useful.

Trace flag described:
https://dev.to/finallynero/redux-action-stack-trace-1m0d
https://blog.logrocket.com/redux-devtools-tips-tricks-for-faster-debugging/

**Comment by mrpmorris** [comment]
It looks like a good idea, I'll keep it in mind for when I have some free time again.

For now, write a middleware that writes out the StackTrace whenever an action is dispatched.

**Comment by mrpmorris** [comment]
Added in 5.2

Thanks for making me aware of it!
