### ISSUE TITLE
Question | Parallel.ForEachAsync | Dispatcher.Dispatch

### ISSUE THREAD

**Issue by mozesa** [mrpmorris/Fluxor#264]
Dear @**mrpmorris**,

I would like to say thank you for this implementation.
I bumped into this library at the weekend, but it seems promising to my application.

Briefly, my app communicates via both `ws` and `http`. Ws (`SignalR`) for local UI, using Vuejs, while http serves as an API.
The application itself is a process controller (something resembles to PLC) thus several background workers (`operations`) run concurrently (using `Parallel.ForEachAsync`). All in all, I would like to use `Fluxor` to serve as the single source of truth.

Would it be problematic to call `Dispatcher.Dispatch` method from `operations` (presumably running concurrently on different threads)?

Thanks for your help in advance!

Best Regards,
**András**

**Comment by mrpmorris** [comment]
The library should be thread safe, so let me know if you come across any threading issues and I will fix them.
