### ISSUE TITLE
IEffect in a middleware namespace is still automatically registered

### ISSUE THREAD

**Issue by hillin** [mrpmorris/Fluxor#278]
The intention of the following code snippet, if I understand correctly, an IEffect (as well as other auto-registerable types) that is placed under the namespace where a middleware resides will be excluded in the types to be automatically registered:
https://github.com/mrpmorris/Fluxor/blob/65a96b579af82387ddddacb50d7c76a3b6b3b377/Source/Fluxor/DependencyInjection/ReflectionScanner.cs#L92-L107

However from the implementation of `AssemblyScanSettings.FilterClasses` below we can see they are not effectively excluded:
https://github.com/mrpmorris/Fluxor/blob/65a96b579af82387ddddacb50d7c76a3b6b3b377/Source/Fluxor/DependencyInjection/AssemblyScanSettings.cs#L29-L37

I think the `||` in line 36 should be `&&`.

**Comment by hillin** [comment]
(Background: we are writing a middleware and wish that some of the effect classes used by the middleware are not automatically registered by Fluxor, rather let the middleware to control them).

**Comment by mrpmorris** [comment]
I'm unable to reproduce this.

The exclusion works on namespace. Is the namespace of the effect either the same or a sub of the namespace the middleware is in?

**Comment by mrpmorris** [comment]
Can you provide a repro for this?
