### ISSUE TITLE
.NET 6 support?

### ISSUE THREAD

**Issue by sbhamad** [mrpmorris/Fluxor#303]
IHello thanks for this great library. I plan to use it within MAUI Blazor (hybrid) but since i am a .NET newbie, i wonder if this library supports .NET 6? i actually do not yet fully understand the whole .NET target framework moniker/.net standard/.NET 5 or 6 or MAUI yet.

But i just want to know if any C# code that is supporting .NET 5 (such as this library "Fluxor"), will it run unchanged on .NET 6? is recompiling enough? if so then what is stopping Floxor from targeting .NET 6?

Thanks

**Comment by mrpmorris** [comment]
It already targets .net 6 - what makes you believe it doesn't?
