### ISSUE TITLE
Possible typo in 02D-ReduxDevToolsTutorial

### ISSUE THREAD

**Issue by GiannhsR** [mrpmorris/Fluxor#308]
Following the tutorial to [disable ReduxWebTools](https://github.com/mrpmorris/Fluxor/tree/master/Tutorials/02-Blazor/02D-ReduxDevToolsTutorial),  I get the following error:
![image](https://user-images.githubusercontent.com/18198166/167915688-7d30880b-55f1-4e47-8bcb-83b742f85b4b.png)

Replacing it with : 
![image](https://user-images.githubusercontent.com/18198166/167916311-3ba66de9-4494-4ada-883a-5b37bfdcbe47.png)

Seems to solve the issue.

**Comment by mrpmorris** [comment]
I will be doing a 5.4 release soon. Would you like to submit a PR against the `release/5.4` branch?

It only actually needs `"'$(Configuration)`==`Debug`"`

**Comment by GiannhsR** [comment]
Sure, I will give that a try.
