### ISSUE TITLE
Consider adding StoreDisposingAction

### ISSUE THREAD

**Issue by diegofrata** [mrpmorris/Fluxor#310]
I am using effects to subscribe to Observables, but when a circuit is being closed in Blazor Server and the store is being disposed, there's no built in action to represent this event. I think it would be useful as it would give developers an opportunity to deterministic clean-up any resources or execute some final side effects.

**Comment by mrpmorris** [comment]
Shouldn't that be done in the circuit? After all, the circuit ultimately has to notify the store the user is gone.

**Comment by diegofrata** [comment]
You're right, I managed to accomplish it using a circuit handler. I will close this issue.
