### ISSUE TITLE
Documentation Suggestion on best practices around using IAsyncEnumerable<T>

### ISSUE THREAD

**Issue by Giszpenc** [mrpmorris/Fluxor#316]
Hi,

There is a fairly large body of examples online on an a use case where you GetAllFoos which returns a List<Foo>() and is updated on the UI.  However, some functions are just GetFoos which (yied) returns a stream of Foos.

It would be great to see an example using this pattern.
Microsoft itself could change the default page from getting a List<WeatherData> to getting an IAsyncEnumerable<WeatherData>.
But with Fluxor, Is there a WeatherStreamState for Begin, (Cancel) and End the stream as well as a WeatherDataState?  
Anyway, an example would be nice.

Thanks!
Vlad

**Comment by mrpmorris** [comment]
Your effect should consume the stream and periodically dispatch actions to update the state.
