### ISSUE TITLE
Question - Singleton

### ISSUE THREAD

**Issue by djjohnson-net** [mrpmorris/Fluxor#330]
I have been looking all over to find an example of using Fluxor State as a Singleton. Can someone direct me in the right direction?  (I'm using Blazor Server)I would like the state to be shared across the whole app including users.  That's why I'm thinking Singleton. Maybe there is a better way with Fluxor? Any suggestions...

**Comment by mrpmorris** [comment]
services.AddFluxor(x => x.WithLifetime(StoreLifetime.Singleton));

**Comment by djjohnson-net** [comment]
Thanks for the suggestion. Does that make all the State objects as Singletons? I'm looking for a solution that will allow me to use Scoped and Singletons depending on how I need them to work.
