### ISSUE TITLE
Add event for specific action on Dispatcher

### ISSUE THREAD

**Issue by BISmb** [mrpmorris/Fluxor#338]
Hello,

Sometimes I would like to be notified of a specific action only (within my Blazor component). I was wondering if something like the below could be added to the Dispatcher?

```csharp
Dispatcher.On<MyAction>(_ => DoSomeLogic());
```

Currently, I use an extension method on the Dispatcher class to get this functionality.

```csharp
public static void OnActionDispatched<TAction>(this IDispatcher dispatcher, Action actionToRun)
{
    dispatcher.ActionDispatched += (sender, args) =>
    {
        if (args.Action.GetType() == typeof(TAction))
            actionToRun();
    };
}
```

Does this type of addition make sense with the architecture or Fluxor? I can work on an example PR if need be.

**Comment by mrpmorris** [comment]
This already exists...
https://github.com/mrpmorris/Fluxor/blob/master/Source/Tutorials/01-BasicConcepts/01E-ActionSubscriber/README.md

**Comment by BISmb** [comment]
Ah sorry, I forgot about the ActionSubscriber.
