### ISSUE TITLE
Question regarding state in collections

### ISSUE THREAD

**Issue by FLAMESpl** [mrpmorris/Fluxor#339]
Hello, I am new to flux pattern.
I have read fluxor tutorials and while they are super clear I am still missing one piece - how to manage state nested in collections?
State objects are just singletons so I cannot share the same class for every item in the collection. In particular, how do I do this in blazor in a way that change in statte nested in the table would re-render only this particular row?

**Comment by mrpmorris** [comment]
You wouldn't only re-render the one row, because you could never be certain that another piece of the UI doesn't do something like sum up values of all rows.
