### ISSUE TITLE
Community

### ISSUE THREAD

**Issue by pm64** [mrpmorris/Fluxor#34]
My feeling is that Fluxor is on track to become an important library in the world of modern .Net development. While interest in this repository seems relatively low (based on stars/watchers), I believe this will increase as related technologies (particularly Blazor) gain adoption, mainly due to a few key advantages Fluxor has over similar libraries and homemade state management patterns.

Knowing this, it seems that some kind of community -- even just a Gitter channel -- would be hugely beneficial as this progression plays out. Fluxor provides the developer with significant flexibility. I'd like to see how others are taking advantage of this, and be able to provide my own insight to other developers based on my experience with Fluxor.

Neither StackOverflow nor this GitHub "issues" page seem to be the most effective way to communicate with other developers using Fluxor. Please consider establishing some kind of online community to facilitate the growth of this important technology.

**Comment by mrpmorris** [comment]
https://gitter.im/mrpmorris/fluxor
