### ISSUE TITLE
Feature: provide a way to supply IStateChangedNotifier to FluxorComponent

### ISSUE THREAD

**Issue by johnbaro** [mrpmorris/Fluxor#340]
I want to encapsulate all state into a Facade, including IState<T>.

This is not possible with `FluxorComponent` as relies on an `IStateChangedNotifier` member to be present.

Would it be accepted if I opened a PR to support the following which would be integrated into the collection of states

```csharp
protected IEnumerable<IStateChangedNotifier> States { get; }
```

**Comment by mrpmorris** [comment]
Components should only subscribe to parts of state they are interested in, not everything.

**Comment by johnbaro** [comment]
I misspoke sorry, I meant that I want to encapsulate all relevant state for a single entity (Todo) into a facade.
So the interface might look like:
```csharp
public interface ITodoFacade
{
    void Load();    
    Todo Get(string id);
    IState<TodoState> State { get; }
    // etc..
}
```

**Comment by mrpmorris** [comment]
Can't you also implement IStateChangedNotifier on that and FluxorComponent will pick it up?

**Comment by johnbaro** [comment]
Yes, for some reason when I looked at the code it looked like a more complex interface.
Closing this I guess.
Thanks.

**Comment by mrpmorris** [comment]
Just to be clear.

I think if you descend your interface from IStateChangedNotifier, *then* FluxorComponent/FluxorLayout will detect it when it scans for injected properties and will automatically re-render when it triggers its event.

**Comment by johnbaro** [comment]
Yes,  that worked perfectly thanks,  5 lines and done.
Thanks again.
