### ISSUE TITLE
[Docs] Component not derived from `FluxorComponent`

### ISSUE THREAD

**Issue by lonix1** [mrpmorris/Fluxor#349]
I've a component derived from a class other than `FluxorComponent`.The docs [state](https://github.com/mrpmorris/Fluxor/blob/f1bf7ce0df0d4bbcf8125b8dca8df6af603eda26/Source/Tutorials/02-Blazor/02A-StateActionsReducersTutorial/README.md#displaying-state-in-a-component):

>Also, add the following line to the top of the razor file
>
>`@inherits Fluxor.Blazor.Web.Components.FluxorComponent`
>
>Note: This is required to ensure the component re-renders whenever its state changes. If you are unable to descend from this component, you can instead subcribe to the `StateChanged` event and execute `InvokeAsync(StateHasChanged)`. If you do use the event, remember to implement `IDisposable` and unsubscribe from the event too, otherwise your app will leak memory.

Does someone have an example of what that looks like?

**Comment by mrpmorris** [comment]
Any time you inject `IState<Whatever>` it has an event on it that you can subscribe to.  Make sure you unsubscribe when your component is disposed.

**Comment by mrpmorris** [comment]
That is spot on!

You could also use this to subscribe to all state properties in one go and dispose the IDisposable it returns when finished. 

https://github.com/mrpmorris/Fluxor/blob/master/Source/Lib/Fluxor/StateSubscriber.cs#L30

**Comment by neozhu** [comment]
> That is spot on!
> 
> You could also use this to subscribe to all state properties in one go and dispose the IDisposable it returns when finished.
> 
> https://github.com/mrpmorris/Fluxor/blob/master/Source/Lib/Fluxor/StateSubscriber.cs#L30

Can you give me an example of how to correctly subscribe to an IState<T> state value without inheriting from FluxorComponent?
