### ISSUE TITLE
IStateSelection memory leak (BindingFlags.FlattenHierarchy?)

### ISSUE THREAD

**Issue by naice** [mrpmorris/Fluxor#353]
Hi, 

I've found out that if you not derive _**directly**_ from FluxorComponent (i have a base component public class LocalizedFluxorComponent :  FluxorComponent) a injected IStateSelection creates a memory leak. 

I haven't had time yet to dig entirely into the code but I am assuming thats a problem with reflection. But i guess that line 
https://github.com/mrpmorris/Fluxor/blob/392907b6bd323d1fedda3992d5a828f483c64a65/Source/Lib/Fluxor/StateSubscriber.cs#L64
might be the problem. So I was asking myself why won't you use BindingFlags.FlattenHierarchy to get all properties?

**Comment by mrpmorris** [comment]
Ah yes, I see the problem.

I think the correct fix is to remove `DeclaredOnly`.

If you fancy submitting a PR into https://github.com/mrpmorris/Fluxor/tree/release/5.6 I'll gladly accept it.

**Comment by naice** [comment]
For the moment I've setup a reproduction project (https://github.com/naice/FluxorMemoryLeak) if you switch between "Counter" and "Fetch data" and observe the console output (Browser) you can see instances stacking... (while clicking on UPDATE COUNT)

I will do but i am currently unsure if this line really IS the problem. I am gonna check out and investigate.

**Comment by mrpmorris** [comment]
Not yet, sorry

**Comment by mrpmorris** [comment]
Fixed in 5.6, thank you for letting me know and for creating the repo!
