### ISSUE TITLE
Redux DevTool automatically opt in to UseRouting

### ISSUE THREAD

**Issue by EDuToit** [mrpmorris/Fluxor#360]
When I ran my project in Debug mode, I opted into UseRouting and used it extensively.

Unfortunately, I never went through opting into it when I was building for Release (as the #if Debug removed the automatic subscription ) 

I am not sure how you might want to go forward with notifying the user base.

https://github.com/mrpmorris/Fluxor/blob/392907b6bd323d1fedda3992d5a828f483c64a65/Source/Lib/Fluxor.Blazor.Web.ReduxDevTools/OptionsReduxDevToolsExtensions.cs#L27

**Comment by mrpmorris** [comment]
ReduxDevTools really should never be released.
Routing should be used in both debug/release or in neither, and has nothing to do with RDT, so should be registered separately.

**Comment by mrpmorris** [comment]
Yes, I hadn't considered the negative case. Thanks!

**Comment by mrpmorris** [comment]
No idea why this got closed again.

**Comment by mrpmorris** [comment]
Fixed in 6.0
