### ISSUE TITLE
Effect executed later than expected on page refresh

### ISSUE THREAD

**Issue by alexandrutatarciuc** [mrpmorris/Fluxor#361]
On my page, in OnInitialized I dispatch an Action `StateLoadAction` with no reducer and an effect that makes an API call to populate a list. When I navigate to this page from another one (thus `StoreInitializedAction` was called) no issues whatsoever:
- Dispatch called
- Effect called
- Page rendered

However, when I refresh the page, I get this:
- Dispatch called
- Page rendered
- Effect called
It wouldn't be an issue since in my store I have a `IsLoading` property and in the effect I dispatch an action to set it to true and when I get my data from the API I set it to false. Nonetheless, the state changes do not refresh the UI, in fact, it looks like I just have the initial state all the time.

Can you help me understand why this happens? Any idea is appreciated.

**Comment by mrpmorris** [comment]
Can you send me a repro?

**Comment by alexandrutatarciuc** [comment]
I've looked more into this. The issue lies in an abstract ComponentBase that I have to inherit.
In a nutshell, I am using a library that makes use of Fluxor itself, but also exposes the functionality of Fluxor to anyone using this library.  There's a ComponentBase that has this implementation:

```
public abstract class MyComponentBase : OwningComponentBase, IDisposable
{
    private readonly List<IStateChangedNotifier> _fluxorStates = new();
    
    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            RegisterFluxorStates();
        }
    
        await base.OnAfterRenderAsync(firstRender);
    }

    private void RegisterFluxorState(IStateChangedNotifier state)
    {
        state.StateChanged += StateChanged;
    }

    private void RegisterFluxorStates()
    {
        var properties = GetType()?.GetProperties(BindingFlags.FlattenHierarchy | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.Public);
        if (properties == null)
        {
            return;
        }

        foreach (var propertyInfo in properties.ToList())
        {
            if (propertyInfo.PropertyType.Name.Contains("IState"))
            {
                var value = propertyInfo.GetValue(this);
                if (value is IStateChangedNotifier stateChangedNotifier)
                {
                    _fluxorStates.Add(stateChangedNotifier);
                    RegisterFluxorState(stateChangedNotifier);
                }
            }
        }
    }

    private async void StateChanged(object? sender, EventArgs args)
    {
        await InvokeAsync(StateHasChanged);
    }

    void IDisposable.Dispose()
    {
        foreach (var state in _fluxorStates)
        {
            state.StateChanged -= StateChanged;
        }
    }
}
```
If I inherit from FluxorComponent rather than from ComponentBase, the issue disappears.
I am not responsible for this implementation, but do you have any suggestion on how this can be properly implemented or if there's any guideline on how to expose Fluxor features?

There's some code that will help you visualize the issue here:
https://github.com/alexandrutatarciuc/FluxorIssue

**Comment by alexandrutatarciuc** [comment]
I don't know if I made it any clearer, but I need my components to inherit from MyComponentBase, whereas MyComponentBase must inherit from OwningComponentBase, thus it cannot inherit from FluxorComponent. How to I properly subscribe them to state changes so I can call StateHasChanged.

**Comment by mrpmorris** [comment]
Have you tried re-using the code from FluxorComponent inside your own base component?

https://github.com/mrpmorris/Fluxor/blob/master/Source/Lib/Fluxor.Blazor.Web/Components/FluxorComponent.cs

ActionSubscriber and StateSubscription + Dispose are the significant ones.

**Comment by alexandrutatarciuc** [comment]
I will close this issue for now because I don't know when I'll have time to test what you mentioned.
