### ISSUE TITLE
Simple example for unit test

### ISSUE THREAD

**Issue by ABIOLI-COM** [mrpmorris/Fluxor#368]
It should be simple, but I cannot find the way to build up a unit test for a simple component using an IState.  
The simplest test should be to just register a simple object with some values, to be automatically injected in the component, without all the fluxor infrastructure up and running.  
I tried, but now I'm wondering if it's possible...  
Thank you again.

**Comment by mrpmorris** [comment]
1. Create a parameterized constructor that requires the dependencies
2. Set the values from that
3. Pass in mocks from your test

**Comment by ABIOLI-COM** [comment]
I didn't explain myself correctly, probably because I didn't understand well what I had to do myself.  
I solved it, anyway.  
Thank you.
