### ISSUE TITLE
Create EventArgs for state changes to notify which action has been dispatched

### ISSUE THREAD

**Issue by cdie** [mrpmorris/Fluxor#375]
Hi,

I'm having a lot of action/reducers involved in my system.
I wish I could be able to filter some action not only based on state value but also on what action provokes the state changes.

Any chances that the EventArgs on StateChanged events could be specified to also carry the action name ?

**Comment by mrpmorris** [comment]
What user experience are you trying to achieve?

**Comment by cdie** [comment]
I have a lot of components related to the same store with a lot of collections, hence many components trigger the update event but might not be concerned by changes. With the action name, I could filter in my event handlers to avoid updating those components as they're not concerned

**Comment by mrpmorris** [comment]
Do you mean you have state that is a collection (eg dictionary) and each component is only interested in a single entry rather than the whole state?

**Comment by cdie** [comment]
Not at all, I found another way to proceed in fact.

But my issue still remain as an enhancement. My state contains multiples collections of differents objects. And sometimes, I just want to filter state change without having to check the collection

**Comment by mrpmorris** [comment]
Is IStateSelection what you want?

**Comment by mrpmorris** [comment]
Have you tried FluxorComponent.SubscribeToAction?

Does that do what you want? If not then let me know, so I can consider this for V6

**Comment by ewdlop** [comment]
Please consider this feature. I also ran into the same issue where I just want to filter state change without having to check the collection(not dictionaries)

**Comment by mrpmorris** [comment]
Have you tried IStateSelection?
