### ISSUE TITLE
Blazor Hybrid MAUI app - ReducerMethods not being called

### ISSUE THREAD

**Issue by lwinch2006** [mrpmorris/Fluxor#382]
I'm testing Fluxor with Blazor Hybrid app. 
And it looks like methods decorated with [ReducerMethod] attribute is not being called.

Setup in MauiProgram.cs
``` csharp
		builder.Services
			.AddFluxor(options =>
			{
				options.WithLifetime(StoreLifetime.Singleton);
				options.ScanAssemblies(typeof(AppStore).Assembly);
			})
			.AddScoped(sp => new HttpClient { BaseAddress = new Uri("https://localhost") })
			.AddBlazorWebViewDeveloperTools()
			.AddMauiBlazorWebView();
```

Defined action
``` csharp
public record ClearUserReadAction
{
	public ClearUserReadAction()
	{
		Console.WriteLine("ACTION CREATED");
	}
}
```

Defined reducer
``` csharp
	[ReducerMethod(typeof(ClearUserReadAction))]
	public static AppStore ReduceClearUserReadAction(AppStore appStore)
	{
		Console.WriteLine("ACTION PROCESSED");
		
		return appStore with {IsLoading = true, UserRead = null, Elapsed = TimeSpan.Zero, ErrorMessage = null };
	}
```

Calling from Razor component
``` csharp
	[Inject] private IState<AppStore> State { get; set; } = default!;
	
	[Inject] private Fluxor.IDispatcher Dispatcher { get; set; } = default!;

	private AppStore AppStore => State.Value;




	private async Task Refresh()
	{
		Console.WriteLine("BEFORE ACTION CALLED");
		
		Dispatcher.Dispatch(new ClearUserReadAction());

	}
```

So console prints out `BEFORE ACTION CALLED` AND `ACTION CREATED`, but not `ACTION PROCESSED`.
So I'm concluding that ReducerMethod not being called.

![Screenshot 2022-12-09 at 14 25 23](https://user-images.githubusercontent.com/6912915/206712425-063344c2-f1ce-492d-b94b-b8551b993b07.png)

**Comment by lwinch2006** [comment]
In usual Blazor WASM app all works OK 
![Screenshot 2022-12-09 at 14 42 32](https://user-images.githubusercontent.com/6912915/206715487-fdf8946f-3bb2-4809-b614-781511812cc6.png)

**Comment by mrpmorris** [comment]
Can you provide me with a repro?

**Comment by lwinch2006** [comment]
Hello.
I have created a sample MAUI + Blazor + Fluxor project. 
It is just a sample app generated from Microsoft template with Counter page. 
With Fluxor I created sample IncrementCountAction that should lead to calling ReduceIncrementCountAction, but it is not.
Incrementing count with local function works normally.
Tested for Mac Catalyst, iOS and Android platforms

Link to repo:
https://github.com/lwinch2006/TestBlazorMauiWithFluxor

Interface:
<img width="497" alt="Screenshot 2022-12-11 at 21 56 44" src="https://user-images.githubusercontent.com/6912915/206929021-1f098aa4-242f-4ee0-ac03-05bf49b080d4.png">

**Comment by mrpmorris** [comment]
Have you added a <StoreInitializer> component somewhere, such as `Main.razor`?

**Comment by lwinch2006** [comment]
Oh my bad 😰, nope, the most embarrassing that I added it in WASM app but not added in MAUI app. After this was surprised that all looks good in one app and not working in another.
Everything works great now, sorry for bothering.

**Comment by mrpmorris** [comment]
It's not a bother at all.  This step is so infrequent it is easily forgotten :)
