### ISSUE TITLE
Add an option to ReduxDevTools to ignore some actions

### ISSUE THREAD

**Issue by cdie** [mrpmorris/Fluxor#383]
I have some actions that only triggers effect.
Because of that, I don't want to register them in ReduxDevTools.

As of today, it doesn't seems that I can mark those actions to be ignored in ReduxDevTools

**Comment by mrpmorris** [comment]
There is a  option for this on RedixDevTools, so I'll keep it on my to do list.

actionsDenylist

**Comment by mrpmorris** [comment]
Fixed in 6.0
