### ISSUE TITLE
Remove Newtonsoft.Json dependency and use built-in System.Text.Json instead.

### ISSUE THREAD

**Issue by Alimzfr** [mrpmorris/Fluxor#386]
It reduces the size of the Blazor applications.
**Newtonsoft.Json** library used in **Fluxor.Blazor.Web.ReduxDevTools**.

**Comment by mrpmorris** [comment]
It is my intention, but you shouldn't be including DevTools in your released product anyway, so size should be irrelevant.

**Comment by mrpmorris** [comment]
Fixed in 6.0
