### ISSUE TITLE
Add callback on effects

### ISSUE THREAD

**Issue by Eits-Ian** [mrpmorris/Fluxor#39]
Hi,

I have 3 trees and 1 paged list, the trees branches all load on demand and using the state datasource causes them to refresh, I have used an event aggregator to publish a message to tell the handler to get the list from state and use the property in the code behind to bind to the tree. I can now add nodes to this without the refresh. If you were able to subscribe to a call back on the Effect it would be a little neater.

Ian.

**Comment by mrpmorris** [comment]
What do you mean it causes them to refresh? Do you mean rerender the component? If so, that's the desired effect, why wouldn't you want that to happen?

**Comment by Eits-Ian** [comment]
You have a tree with say 4 branches, on clicking of the arrow to expand, I retrieve this data from the api, append the nodes to the tree and it expands. However it will rerender the component, the expanded node is still collapsed. If I am updating 1 tree from the selection made on another tree then then full component rerender would be the desired effect, but not for a branch expand.

**Comment by mrpmorris** [comment]
Looks like you need to store `bool Expanded` against each node in your state

**Comment by Eits-Ian** [comment]
I do, 

IsExpanded
HasChild
IsSelected
IsChecked

I'll just send a message to the view after the new data is in the store and create a copy for the view to work with, once I have it all fleshed out I'll revisit.

**Comment by mrpmorris** [comment]
If the state is correct then the problem lies in the UI. Are you using `@key` on your tree elements that are linked to the data?

**Comment by mrpmorris** [comment]
I'll close this for now. Let me know if you find something in Fluxor that needs looking at
