### ISSUE TITLE
Subscribe to Action in ASP.NET Blazor server

### ISSUE THREAD

**Issue by nthompson0033** [mrpmorris/Fluxor#396]
Hello I have used Fluxor server to communicate between two Hosted background services in an ASP.NET Blazor server applixcation

My Fluxor service is installed as a singleton

Each action subscription is dispatched but not actioned untill a browser connects to the application, but I need the services to run with or without a user interface

Is this by design, or a feature of the singleton service is there an alternative configuration for the fluxor service, please advise
many thanks I can supply any code if you let me know what you need many thanks Nick.

**Comment by nthompson0033** [comment]
Hi It may be an issue with the location of StoreInitialiser (which is in app.razor) any suggestion would be great I will experiment further when I am able too Nick

**Comment by mrpmorris** [comment]
Fluxor is thread safe, but I don't think it would be a very effective way of having multiple users share a single state.

In answer to your question, you can call IStore.InitializeAsync() when your server starts.

**Comment by nthompson0033** [comment]
Thankyou Peter for your quick response, I was having a quick panic as my whole project design was falling apart, I have three hosted services & calling ISore.InitializeAsync as you suggest is working perfectly

I have many Process variables that need to be shared and so I use the Microsoft Imuutable Dictionary in my singleton store and subscribe to the Action used to update the same store in each process

All Blazor users have identical access to the store also.

I know it is quirky it is my first  Blazor Server project targeted at an embedded Debian Amplicon Impact PC.
