### ISSUE TITLE
Simple examples for testing

### ISSUE THREAD

**Issue by eharbitz** [mrpmorris/Fluxor#397]
It would be great to have some simple examples in the documentation that demonstrates how to make simple tests:

For example:
- Test that a component is renders differently with different Fluxor state
- Test that a component re-renders with correct data when the Fluxor state is changed
- Test that the state is updated correctly when actions are dispatched (no component involved, just unit testing actions)

Thank you!

**Comment by mrpmorris** [comment]
Fluxor is UI agnostic. To test Blazor components, use BUnit.

**Comment by eharbitz** [comment]
Ok, I see.

It is just a bit hard to figure out how to set everything up with services and initializing the Fluxor store in the test framework.

This seems to be a common problem given that there are already at least four other closed issues on this: https://github.com/mrpmorris/Fluxor/issues/368, https://github.com/mrpmorris/Fluxor/issues/187, https://github.com/mrpmorris/Fluxor/issues/211, https://github.com/mrpmorris/Fluxor/issues/15.

**Comment by mrpmorris** [comment]
Thanks for sharing!
