### ISSUE TITLE
System.InvalidOperationException error

### ISSUE THREAD

**Issue by AresDev** [mrpmorris/Fluxor#40]
Hi,

I was able to get this up and running and everything works like charm, but passed some random time debugging my app, I'm getting an System.InvalidOperationException error and then it closes my debug session.

This is what I'm getting from the output:
An unhandled exception of type 'System.InvalidOperationException' occurred in Fluxor.dll
DisposableCallback with Id "StateSubscriber.Subscribe" was not disposed.

Do you have any idea what could I be doing wrong?

Thanks!

PS: awesome library!

**Comment by mrpmorris** [comment]
Hi.

Are you descending from FluxorComponent or FluxorLayout, overriding `Dispose(bool disposing)` but not calling `base`?

**Comment by AresDev** [comment]
Hey @mrpmorris thanks for that quick response, I fixed it was a silly mistake of mine. I was overriding onInitializedAsync to be able to await an initialization process but I was calling the synchronous method of the parent.

**Problem**
protected override async Task OnInitializedAsync()
    {
        base.OnInitialized();
   }

**Fix**
protected override async Task OnInitializedAsync()
	{
		await base.OnInitializedAsync();
        }

Thanks again!

**Comment by mrpmorris** [comment]
Ah, I've seen this done before :)

**Comment by brettwinters** [comment]
great library @mrpmorris!  - I've just fallen for this one too. 

To make your library more mistake / idiot proof (since I think only calling base on SetParameters() is important so we've got lazy) would it make sense to initialise your state `StateSubscription = StateSubscriber.Subscribe(this, _ => InvokeAsync(StateHasChanged));` in a constructor?

**Comment by mrpmorris** [comment]
Our can't be done there because the states are objected by blazor after the component is created.
