### ISSUE TITLE
Minified code outside of NODE_ENV

### ISSUE THREAD

**Issue by monderino** [mrpmorris/Fluxor#405]
Hi,

First of all thanks for this great library. It makes my day easier ;)

I got an error in the browser console:
You are currently using minified code outside of NODE_Env === "production". This means that you are running a slower development build of Redux. You can use loose-envify for browserify or setting mode to production in webpack to ensure you have the correct code for your production build.

I do not use weback. For now I updated to the latest version and disabled the DevelopmentTools in production, but not sure if this solve the issue. 

Any Ideas for that?

Thanks and best regards.
Sven

**Comment by mrpmorris** [comment]
Hi Sven.

I don't think it's a good idea to include dev tools in a release build.

**Comment by monderino** [comment]
Yes, I disabled it. 

I think it solved my issue.

Thank you.
