### ISSUE TITLE
Add GitHub project description

### ISSUE THREAD

**Issue by jzabroski** [mrpmorris/Fluxor#41]
Please add "Fluxor is a zero boilerplate Flux/Redux library for Microsoft DotNet." to the top of the GitHub page.

**Comment by jzabroski** [comment]
![image](https://user-images.githubusercontent.com/447485/84168006-e8e45e80-aa44-11ea-947e-655b2fe1a172.png)

**Comment by mrpmorris** [comment]
Done, thank you!
