### ISSUE TITLE
Dependency Injection & GetInitialState

### ISSUE THREAD

**Issue by daminee80** [mrpmorris/Fluxor#42]
Is it possible to inject a dependency into the initial state?

Assuming the following Feature: 
 ``` 
public class AppFeature : Feature<AppState>
{
     private readonly IImportantDependency _importantDependency;

     public override string GetName() => "App";

     public AppFeature(IImportantDependency importantDependency)
     {
         _importantDependency = importantDependency;
     }
     protected override AppState GetInitialState()
     {
         return new AppState(_importantDependency);
     }
 }
```
Since base class `Feature<TState>` calls the virtual method GetInitialState from its constructor, the GetInitialState method will get called before the derived class is fully initialized (before it's constructor is called) and thus before the IImportantDependency is resolved.

I could try to inject the IImportantDependency in `: Effect<StoreInitializedAction>`
and then `Dispatch` and action with the IImportantDependency as a constructor parameter on the action, but the `Task HandleAsync(StoreInitializedAction action, IDispatcher dispatcher)`  gets called after the IImportantDependency is required.

**Comment by mrpmorris** [comment]
State should not have dependencies.

If you need state from somewhere else, you can create an EffectMethod that is triggered by StoreInitializedAction. The Effect can have that dependency injected, take the state it needs, and fire off an action to set up the state you need.

**Comment by daminee80** [comment]
I think that's a great suggestion.  I tried both methods, `State.Value.HasInitialized` and the `FakeLocalizer` and both seem to work just fine.

Thanks again.
