### ISSUE TITLE
Support F# records as FeatureState

### ISSUE THREAD

**Issue by mrakgr** [mrpmorris/Fluxor#429]
> A parameterless constructor is required on state for determining the initial state, and can be private or public.

I meant to define the reducers on the F# side, and had intended to define feature state as records, but then I read this line. Unfortunately, it is not possible to define a constructor on an F# record. Is there a way to get around this restriction?

**Comment by mrakgr** [comment]
Also, wouldn't the same issue apply to C# records?

**Comment by mrpmorris** [comment]
FeatureState attribute lets you specify the name of a static method instead, does that help?

**Comment by mrakgr** [comment]
Yes, thank you.
