### ISSUE TITLE
IStateSelection resolving for unit tests

### ISSUE THREAD

**Issue by PikoooX** [mrpmorris/Fluxor#437]
I got a situation that I am unsure how to handle. I have a component that has two state selectors which are generic and of the same type IStateSelection<State<T>, int> and are in the same parent state. I am using BUnit tests with Moq, is there a way to register a service or a state in the test context that would result in these two selectors receiving different values? I can't really use ques for mocking setup cause that would be quite hard since the states are being called in multiple places so there is no way to determine the order of calls.

**Comment by mrpmorris** [comment]
I'm sorry, I don't know the answer to this question. Have you asked in Moq?

**Comment by PikoooX** [comment]
I have found a hacky way arround it, I guess there is no real way of resolving it. You can always box those two values in a record or a class and then do it that way. I will see if it can be done through Moq.

**Comment by mrpmorris** [comment]
Please keep me updated, I am very interested.
