### ISSUE TITLE
Find component causing OnInitialized missing error

### ISSUE THREAD

**Issue by mohaaron** [mrpmorris/Fluxor#443]
I have a fairly complex hierarchy of components and am getting an error that OnInitialized is not being called in an overidden OnInitialized. Is there anyway I can see in a stacktrace what the component is that's missing the call to base.OnInitialized()? I've been unable to find the offending component.

**Comment by mrpmorris** [comment]
Unfortunately, no, because this is an exception that is thrown when an object is garbage collected.  I'm afraid you're going to have to do a FindAll and search for OnInitialized
