### ISSUE TITLE
.NET 8 server-side rendering doesn't work with Fluxor

### ISSUE THREAD

**Issue by guythetechie** [mrpmorris/Fluxor#451]
I created a project using the default .NET 8 Blazor Web App template. I then modified the counter page to use Fluxor for incrementing. Unfortunately, incrementing by clicking on button does not work.

Because the default template uses server-side rendering, ``ComponentBase.OnAfterRender`` [is not called](https://github.com/dotnet/AspNetCore.Docs/pull/30098/files#diff-901b5c1cb3df671cf6cf3a99588ef5d90ff0e9c760bbbd0aa0f97cdeceec70adR254) and the Fluxor ``IStore`` doesn't get initialized.
![image](https://github.com/mrpmorris/Fluxor/assets/31325620/ef78c42a-8375-4b62-83db-c6dd450fc395)

To fix it, I simply injected and initialized ``IStore`` in my component.
```csharp
    [Inject]
    private IStore Store { get; set; } = default!;

    protected override async Task OnInitializedAsync()
    {
        await base.OnInitializedAsync();
        await Store.InitializeAsync();
    }
```

Just wanted to raise this as Blazor in .NET 8 defaults to server-side rendering. There's a good chance most .NET 8 Fluxor projects will run into this.

Here are sample repos that illustrate the issue:
- [Without fix](https://github.com/guythetechie/FluxorTest/blob/master/Components/Pages/Counter.razor).
- [With fix](https://github.com/guythetechie/FluxorTest/blob/fix/Components/Pages/Counter.razor).

**Comment by guythetechie** [comment]
> I suppose you'd have to resolve IStore in your app boot up and call InitializeAsync in there?

That's right. It's a trivial fix if you know what the problem is. That said, anyone using Fluxor + BSSR will run into the issue, so might be worth calling this out somewhere. Not sure how easy it is to address directly in the library.

**Comment by mrpmorris** [comment]
I've not really tried BSSR, I will get around to it :)

**Comment by michaelvolz** [comment]
just fyi: `OnInitializedAsync` does not seem to work in the latest build, but with `OnAfterRenderAsync` it works fine. Thanks for the tip!

**Comment by mrpmorris** [comment]
OnAfterRender* doesn't execute in SSR.

**Comment by michaelvolz** [comment]
I am using it on my machine. Works perfectly. Server/WebAssembly and Auto.
