### ISSUE TITLE
StoreInitializer not working in Balzor .net 8

### ISSUE THREAD

**Issue by dbrighton** [mrpmorris/Fluxor#460]
I'm using with Blazor Server-Side (.net 8). Not getting any exceptions, but it's not working either.  I think the problem is with the new App.razor (<StoreInitializer></StoreInitializer>) component in .net 8.

here is my App.razor

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <base href="/"/>
    <link rel="stylesheet" href="bootstrap/bootstrap.min.css"/>
    <link rel="stylesheet" href="app.css"/>
    <link rel="stylesheet" href="Blazor8Demo.styles.css"/>
    <link rel="icon" type="image/png" href="favicon.png"/>
    <link href="_content/MatBlazor/dist/matBlazor.css" rel="stylesheet"/>
    <script src="_content/MatBlazor/dist/matBlazor.js"></script>
    <HeadOutlet/>
</head>

<body>
<StoreInitializer></StoreInitializer>
<Routes/>
<MatPortalHost/>
<MatToastContainer/>
<Toaster/>
<script src="_framework/blazor.web.js"></script>
<script src="_content/Fluxor.Blazor.Web/scripts/index.js"></script>
</body>

</html>

**Comment by stagep** [comment]
Do you have 

`<Fluxor.Blazor.Web.StoreInitializer />`

in your Routes.razor?

**Comment by Rhywden** [comment]
I'm also confused why you're talking about "Server-side" but are using Javascript?

**Comment by WhitWaldo** [comment]
This should be tentatively fixed with #481

**Comment by ChuckBryan** [comment]
> Do you have
> 
> `<Fluxor.Blazor.Web.StoreInitializer />`
> 
> in your Routes.razor?

This helped me with my example. I was following the Counter example in the docs which said to put that component in the App.razor. Thanks!
