### ISSUE TITLE
Fluxor dont work with new template .Net 8 and InteractiveServerRenderMode

### ISSUE THREAD

**Issue by MadnessAN** [mrpmorris/Fluxor#462]
Hello,

With the new .NET template, it appears that Fluxor is not being initialized when the AddInteractiveServerRenderMode is activated.

**Comment by MadnessAN** [comment]
I have tried many things to fix the issue. My analysis led me to understand that the onAfterRenders and OnAfterRenderAsync (StoreInitializer) methods are never triggered. This starts from the moment you instantiate the Blazor AddInteractiveServerRenderMode in .NET 8. I attempted to upgrade to .NET 8 Fluxor and Fluxor Blazor Web. I made various rendering attempts to successfully trigger the onAfterRenders which initializes the store, but without success."

**Comment by Rhywden** [comment]
See #459
