### ISSUE TITLE
Fluxor breaks ErrorBoundary in Blazor Wasm

### ISSUE THREAD

**Issue by cluka** [mrpmorris/Fluxor#463]
I'm having a problem where the error page of ErrorBoundary does not show when using Fluxor in Blazor wasm 8.

I think this is because the exception is caught during control render sequence. So when Using
`Dispatcher.Dispatch(action)`

and an exception occurs, I get

`Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
  Unhandled exception rendering component: Exception of type 'MyApp.Errors.ServerValidationException'`

and I get

`An unhandled error has occurred. Reload`

message and the error page of the ErroBounday is NOT shown.

But if I don't use Fluxor and only do a classic service call, the error page of the ErrorBoundary is show.

Is there a way to fix this?

**Comment by 3dots** [comment]
.NET 8 has a way to bubble an exception to the ErrorBoundary.

![image](https://github.com/mrpmorris/Fluxor/assets/6589306/086f40b2-71e0-4998-9bb4-36615b15b848)
![image](https://github.com/mrpmorris/Fluxor/assets/6589306/1e379b6b-0c9e-47ab-8f91-be94ebe59155)

**Comment by mrpmorris** [comment]
Effects are not called within a component, they run in the background as if no UI even existed, so there are no boundaries.

StoreInitializer has a callback where you can trigger some code when an unhandled exception is encountered in an effect, but that won't help with boundaries.

Your state is an app-wide thing. If you experience an error that you weren't expecting then you cannot guarantee that data is now in a consistent and acceptable state - which means your app state in general cannot be trusted.

**Comment by EliseoDiegoViola** [comment]
Adding a comment here since the last one is pretty new.


Im having this same issue, but there is something that I dont understand.

@mrpmorris 
> Effects are not called within a component, they run in the background as if no UI even existed, so there are no boundaries.

The `Fluxor.Blazor.Web.StoreInitializer` is a component, and is the one that catches the exceptions inside the effects and re-throws them inside the render cycle (OnAfterRender specifically). So if the ErrorBoundary->ChildContent  have the store initializer inside it should work correctly, right? Because it isn't.

**Comment by tobias-andraschko-mint** [comment]
@mrpmorris 
Can the stacktrace of this exception be preserved somehow to show which effect handler has thrown the exception?

At the moment its just this
```
Unhandled exception rendering component: Status(StatusCode="Internal", Detail="Test")
Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Test")
at Fluxor.Blazor.Web.StoreInitializer.OnAfterRender(Boolean firstRender) in C:\Data\Mine\Code\Fluxor\Source\Lib\Fluxor.Blazor.Web\StoreInitializer.cs:line 57
 at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleAfterRender.OnAfterRenderAsync()
 at Microsoft.AspNetCore.Components.Rendering.ComponentState.NotifyRenderCompletedAsync()
```

What if you would use directly rethrow the exception when its catched? Using throw inside the catch block in the StoreInitializer?

**Comment by mrpmorris** [comment]
I really should have embedded the original exception rather than rethrowing it.

You can set the StoreInitializer UnhandledException callback to receive the exception and optionally handle it yourself.
