### ISSUE TITLE
Deadlock when dispatching from store/feature events

### ISSUE THREAD

**Issue by mrpmorris** [mrpmorris/Fluxor#474]
If the handlers on Dispatcher.ActionDispatched or Feature.StateChanged events dispatch another action on a different thread then a deadlock occurs.

**Comment by aleroca96** [comment]
Hi
First of all, thanks for building this library. It has been really useful on legacy Winforms projects.

Do you know if/when this issue will be fixed and if you have found a temporary solution to it?

Many thanks!

**Comment by mrpmorris** [comment]
I have a potential solution but need to stress test it because threading.

What version of .net are you using? It looks like I might only be supporting 6..8

**Comment by aleroca96** [comment]
Im on Net8
