### ISSUE TITLE
Examples are useless

### ISSUE THREAD

**Issue by Sm1le291** [mrpmorris/Fluxor#48]
Examples too simple and do not show real example of usage.
Please provide more complex State, at least 3-4 properties and more actions.
From examples does not clear follows how to use your library.

**Comment by mrpmorris** [comment]
Have you read the accompanying documentation for each sample?

**Comment by Sm1le291** [comment]
@mrpmorris for example I have a UserState with complex property PrivacySettings.
And I want to change PrivacySettings in Settings page. Model for form must contains property for Errors which I can receive from backend, BUT I don't need Errors in usual cases of using  PrivacySettings,
Do I need to use PrivacySettings as part of UserState in this case. 
Do I need to create PrivacySettingsState only for editing them and after update, make changes in UserState.PrivacySettings
And the third way, I can update settings without FLuxor, just using HttpCLient and then if settings were successfully updated, update UserState.PrivacySettings?
I could not find any real cases how to modify data and how to spread changes to States
