### ISSUE TITLE
Test case for dispatcher failure in .NET8 with new render modes 

### ISSUE THREAD

**Issue by mikeppcom** [mrpmorris/Fluxor#487]
[DispatcherTest.zip](https://github.com/mrpmorris/Fluxor/files/15151233/DispatcherTest.zip)

**Comment by mikeppcom** [comment]
Hi Peter,

In server project do you have the code to enables the new interactive render mode

// Add services to the container.
builder.Services.AddRazorComponents()
    .AddInteractiveServerComponents()
    .AddInteractiveWebAssemblyComponents();

Fluxor works fine in .NET8 with the original render mode. The problem is due to the render mode.

Does my example fail for you?

Michael

**Comment by mrpmorris** [comment]
[BlazorFluxorApp.zip](https://github.com/mrpmorris/Fluxor/files/15318285/BlazorFluxorApp.zip)

If you change this counter example and upload then I will do a diff.

**Comment by mikeppcom** [comment]
Hi Pete,

The difference between our test cases is that you have Fluxor in the client part whereas I have it in the server part. If you run the PoCServerAndClient_Fail test case I uploaded to the GitHub you’ll see that the subscribe code breakpoint is never hit.

Michael

***@***.***

**Comment by mikeppcom** [comment]
We have a Blazor server project that been running for several years that uses lots of Fluxor. We are now adding a new function that requires a single component to run on the client (this is for compliance with PCI for credit cards). To do this we are using the new interactive rendering modes. Your example is only using interactive rendering for client components and here Fluxor appears to work. It’s does not work in interactive server components though.

Michael
