### ISSUE TITLE
🤑 Add a sponsor button

### ISSUE THREAD

**Issue by Hona** [mrpmorris/Fluxor#489]

**Comment by mrpmorris** [comment]
I have no idea how to :)

**Comment by Hona** [comment]
step one: setup personal sponsorship 

https://docs.github.com/en/sponsors/receiving-sponsorships-through-github-sponsors/setting-up-github-sponsors-for-your-personal-account

step two: add the button to the fluxor repo

https://docs.github.com/articles/displaying-a-sponsor-button-in-your-repository

**Comment by Hona** [comment]
I've used fluxor for some clients and personal apps, and I believe in supporting open source, so it would be great to support you back - not matter how small!
