### ISSUE TITLE
[Feature Request] Added generation all wrapper with Source Generators

### ISSUE THREAD

**Issue by redradist** [mrpmorris/Fluxor#49]
To reduce boilerplate it would be nice if it would be generated say with Source Generators by annotating the variable with annotation

**Comment by mrpmorris** [comment]
Sorry, I don't know what you are asking for. Could you provide an example?

**Comment by redradist** [comment]
@mrpmorris  I mean to generate all this stuffs https://github.com/mrpmorris/Fluxor/blob/master/Tutorials/01-BasicConcepts/01A-StateActionsReducersTutorial/README.md

`CounterState`, `Feature<CounterState>` and etc.

I just want to write:
```razor
    [FluxorState]
    int Counter { get; }
```

**Comment by mrpmorris** [comment]
It looks like an interesting tool, but isn't suitable for Fluxor because there are lots of ways a coder can structure their app.
