### ISSUE TITLE
Fluxor not updating UI after state change

### ISSUE THREAD

**Issue by robertogonzalezdelarosa** [mrpmorris/Fluxor#490]
Hello, im bulding an aplication using MAUI hibrid blazor and I installed Fluxor for state management, everything works just fine but when I succesfully change the state the changes are not reflected on the UI. the rare thing is if I click random on any part of the app the changes are reflected or if I navigate to another view

Am I missing something?

hope you can help me i very frustrated at this point.

Regards

**Comment by mrpmorris** [comment]
Can you provide a minimal repro?

**Comment by robertogonzalezdelarosa** [comment]
the solution was to move in another razor component the first @if condition otherwise it throws an exception

**Comment by mrpmorris** [comment]
If you descend from my Fluxor component it will handle subscribe/unsubscribe for you. 

I recommend that approach when it is an option.
