### ISSUE TITLE
Enabling Fluxor for lazy-loaded assemblies

### ISSUE THREAD

**Issue by LucaMahler** [mrpmorris/Fluxor#493]
In our project, we have a main WASM project which acts as container for micro frontends. These are being lazy-loaded and are themselves Razor Class Libraries (RCL).

Do you support this use case?

Now, when I use the `.ScanAssemblies(typeof(Program).Assembly), ???) `in the `Program.cs`, there is no way of using the lazy-loaded assembly yet.

**Comment by mrpmorris** [comment]
You'd have to write them as Reducer and Effect subclasses and add them manually to the store and relevant features.

**Comment by martin-allegiance** [comment]
> You'd have to write them as Reducer and Effect subclasses and add them manually to the store and relevant features.

Is it possible to elaborate a bit more on this? We are also in a similar situation and would really appreciate it.

**Comment by OscarLate** [comment]
@mrpmorris how could features/effects be added by Code? Seems very interesting.

**Comment by mrpmorris** [comment]
```c#
	public class IncrementCount { }
	public record MyState(int ClickCount);

	public class MyFeature : Feature<MyState>
	{
		public override string GetName() => "MyFeature";
		protected override MyState GetInitialState() => new MyState(0);
	}

	public class MyFeatureReducer : Reducer<MyState, IncrementCount>
	{
		public override MyState Reduce(MyState state, IncrementCount action) =>
			new(ClickCount: state.ClickCount + 1);
	}
```

Then resolve `IStore` and do this
```c#
			var f = new MyFeature();
			f.AddReducer(new MyFeatureReducer());
			store.AddFeature(f);
```
