### ISSUE TITLE
Thread lock

### ISSUE THREAD

**Issue by tomesendam** [mrpmorris/Fluxor#50]
I made a simple search box that searches trough a list of some items. This code runs fairly fast (~1-2ms).
I added some console output to verify this, those outputs are shown in the chrome console instantly as I type.

And while the console instantly reflects what I type in the UI remains locked up and lags behind severely. 
To make sure I removed all logic from my reducers and just returned the old state. This resulted in reducers that took less than a ms. However the result is the same.

Am I doing something wrong or is this a limit of the Fluxor framework?

```
private void OnSearchTextChanged(ChangeEventArgs e)
        {
            Dispatcher.Dispatch(new SearchInDossierListAction(e.Value.ToString()));
        }
```

**Comment by mpp** [comment]
Hi, I had the same problem doing the same thing. 

I didn't investigate it a lot as I have several different features with they're states. I thought it was slow because of the size and complexity of the overall redux state:

![image](https://user-images.githubusercontent.com/454298/86027364-37f33300-b9f6-11ea-947a-4311283d3bf4.png)

Let me know if you find any solution!

**Comment by JefSchraag** [comment]
In my project, I could make it faster by disabling the dev tools

```csharp
		.AddFluxor(options =>
				{
					options.ScanAssemblies(typeof(Program).Assembly);
					//options.UseRouting();
					//options.UseReduxDevTools();
				});
```

I have not checked but from the difference in performance, I concluded that the `UseReduxDevTools` is always serializing the state at every change.

**Comment by mpp** [comment]
Thanks, I'll give you a feedback as soon as I can test it

**Comment by tomesendam** [comment]
@JefSchraag Disabling it did solve it for me. So it seems like it's an issue with that indeed! Guess that'll just be a problem when debugging then.

**Comment by mrpmorris** [comment]
Redux Dev Tools is designed to accept the full state serialised as json. I don't think there is anything I can do about that except perhaps throttle updates when the same action type is dispatched.
