### ISSUE TITLE
How should one deal with multiple of the same state on the same page?

### ISSUE THREAD

**Issue by pirovorster** [mrpmorris/Fluxor#501]
We currently have a pager component. This component could appear twice on a page.
I've seen people suggest using a dictionary to control the state in such cases?
What I don't like about this approach is the fact that the pager state now needs to be aware of the fact that itself might be used more than once, if that makes sense? So for example if you initially thought you would only have 1 component of said type on a page and later you discover that that is not true, you would have to go redesign your state object, not?

So
- What is the best way to handle multiple of the same state on a page?
- Is there a good example of this somewhere?

**Comment by mrpmorris** [comment]
I agree with the suggestion.
The state isn't 1 pager, it is multiple pagers, so you'll need an ImmutableDictionary

**Comment by pirovorster** [comment]
@mrpmorris thank you, but
do you have some good examples of this?
Is it recommended to use fluxor state for things like reusable components?

**Comment by mrpmorris** [comment]
I don't have an example, no.
