### ISSUE TITLE
Fluxor.Blazor.Web script not found

### ISSUE THREAD

**Issue by Raveen87** [mrpmorris/Fluxor#517]
I'm using .NET 9 and latest Fluxor.Blazor.Web (6.1.0).

I generated a default Blazor Server application through the `Blazor Web App` template.
After that I followed the [official guide](https://github.com/mrpmorris/Fluxor/tree/master/Source/Tutorials/02-Blazor/02A-StateActionsReducersTutorial) on how to add support for Fluxor.Blazor.Web.

The guide doesn't mention anything regarding adding the script tag, but after reading the [Upgrade instructions](https://github.com/mrpmorris/Fluxor/blob/master/Docs/upgrading-instructions.md) I gleaned that I need to do that.
I added it in `App.razor` after the blazor javascript tag, like this:
`<script src="_content/Fluxor.Blazor.Web/scripts/index.js"></script>`

When running the application, nothing happens on pressing the button to increment the counter. Upon inspecting the console there's a warning:

> Loading failed for the <script> with source “http://localhost:5039/_content/Fluxor.Blazor.Web/scripts/index.js”.

I've created a [repository](https://github.com/Raveen87/FluxorBlazorTest) with the complete solution. There are two commits. The first contains just the default template, the [second commit](https://github.com/Raveen87/FluxorBlazorTest/commit/389f06d767862edf86651f7762ead9f5490e3f3f) contains all the changes related to adding Fluxor.

What's causing this issue and how can it be resolved?

**Comment by stagep** [comment]
Move the <Fluxor.Blazor.Web.StoreInitializer /> from App.razor to Routes.razor

**Comment by Raveen87** [comment]
Thank you, that was it. 🙂
Just moving `<Fluxor.Blazor.Web.StoreInitializer />` from `App.blazor` to `Routes.blazor` solved it.
The script reference, like you mention, isn't needed.

The guide states:

> Then we need to ensure the store is initialized. Edit App.razor and at the top of the file add the following mark-up.
> 
> <Fluxor.Blazor.Web.StoreInitializer/>

So the relevant mistake was due to an out-of-date guide.
