### ISSUE TITLE
Value from state is null

### ISSUE THREAD

**Issue by petyusa** [mrpmorris/Fluxor#52]
Hi,

I've started to use Fluxor a few days ago. I'm developing a Blazor Webassembly app. My app calls a web API with a bearer token.

I've created an AuthState class, where the accessToken is stored. I dispatch a LoginAction, call my token endpoint in the Effect class, then dispatch a LoginResultAction, and in the AuthReducer class I create the new state with the token. It works fine, I can display the token in any components, so this part is great.

What I want to achieve, is to use this token in my DelegatingHandler, so when an Http request is sent, it sets the token from the AuthState. But whatever I do, the accessToken is always null in the DelegatingHandler.

Here is my code:
```
public class AuthenticationHandler : DelegatingHandler
{
    private readonly IState<AuthState> _authState;

    public AuthenticationHandler(IState<AuthState> authState)
    {
        _authState = authState;
    }

    protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        var accessToken = _authState.Value.AccessToken;
        request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
        return base.SendAsync(request, cancellationToken);
    }
}
```

When I trying to get the AccessToken, it's value is always null. I tried registering the handler as Transient, it didn't help. (If I hardcode the token, it works fine.)

I'm new to blazor and fluxor as well, maybe I'm missing something, would be great if anyone could help me.

**Comment by mrpmorris** [comment]
Hi

It's actually a bug in .NET that I reported recently here https://github.com/dotnet/aspnetcore/issues/23847

I'd recommend having your own IHttpClientFactory service for creating HttpClient object so you can inject your query status into the header.

Make sure you remember to Dispose the HttpClient instance when you've finished with it.

**Comment by petyusa** [comment]
Thanks, the workaround helped. Hope it will be fixed soon.

**Comment by mrpmorris** [comment]
Could you try registering your handler as Transient, does that solve the problem?

**Comment by petyusa** [comment]
That was my first thought, I've already tried it, as I mentioned it in my question. Now I tried it again to be sure, but accessToken is still null (if I inject the state in my service, it works fine). 

I post my code here:
DelegatingHandler:
```
public class AuthenticationHandler : DelegatingHandler
{
    private readonly IState<AuthState> _authState;
    public AuthenticationHandler(IState<AuthState> authState)
    {
        _authState = authState;
    }

    protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        var accessToken = _authState.Value.AccessToken;
        request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
        return base.SendAsync(request, cancellationToken);
    }
}
```

Registration:
```
public static async Task Main(string[] args)
{
    var builder = WebAssemblyHostBuilder.CreateDefault(args);

    builder.RootComponents.Add<App>("app");

    builder.Services.AddTransient<AuthenticationHandler>();
    builder.Services
        .AddHttpClient("AuthenticatedClient", client =>
        {
            client.BaseAddress = new Uri("https://localhost:45299/");
        })
        .AddHttpMessageHandler<AuthenticationHandler>();
            
    var currentAssembly = typeof(Program).Assembly;
    builder.Services.AddFluxor(options => options.ScanAssemblies(currentAssembly));

    await builder.Build().RunAsync();
}
```

And here's how I use it in a service:
```
protected HttpClient AuthenticatedClient
{
    get
    {
        var client = HttpClientFactory.CreateClient("AuthenticatedClient");
        return client;
    }
}
```

**Comment by mrpmorris** [comment]
Ah yes of course, thanks!

**Comment by mrpmorris** [comment]
What class type do you receive for IHttpClientFactory? Can you use your original code and then register that class as Scoped?

**Comment by mrpmorris** [comment]
The default HttpClientFactory is an internal class, so that's not very helpful. I've reported another bug here https://github.com/dotnet/extensions/issues/3352

**Comment by petyusa** [comment]
Yes, I've just checked, and it's a DefaultHttpClientFactory.

**Comment by mrpmorris** [comment]
@petyusa As an experiment, would you try this?

```
var type = typeof(IHttpClientFactory).Assembly.DefinedTypes.Single(t => t.Name.Contains("DefaultHttpClientFactory"));
services.AddScoped(typeof(IHttpClientFactory), type);
```

**Comment by petyusa** [comment]
Should I just simply add these lines? I have to use AddHttpClient to be able to add a message handler, doesn't it register another IHttpClientFactory? 

By the way, I added these lines, and nothing changed.

**Comment by mrpmorris** [comment]
Let's leave it then. MS has a bug to fix.
