### ISSUE TITLE
Slow ScanAssemblies in large CSB projects

### ISSUE THREAD

**Issue by szmalec** [mrpmorris/Fluxor#54]
Hello.
Recently I wanted to try out using Fluxor.Blazor.Web v3.1.1 in a CSB project that I am currently developing. When I added `builder.Services.AddFluxor(o => o.ScanAssemblies(typeof(Program.Assembly));` it turned out that the the application started about **2 minutes** ...
When I added references to Fluxor.Blazor.Web.csproj / Fluxor.csproj to my project instead of nuget package and when I added simple loging, it turned out that e.g. in `ReducerMethodsDiscovery.DiscoverReducerMethods` parameter `allCandidateTypes` contained 2100 elements and the expression:
`allCandidateTypes.SelectMany(t => t.GetMethods(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.Static))` returned 27760 elements.
Perhaps this is due to the fact that there are many components in the project, which additionally often are based on some abstract class with many methods.
When I added the logging of the results of the mentioned expression, it turned out that (if I'm not mistaken):
* over 12000x there are methods with DeclaringType == Object (e.g. Name == "GetType" or "GetHashCode", etc.)
* over 3000x there are methods with DeclaringType == ComponentBase
* more than 1000x there are methods with DeclaringType == MyComponentBase
* The method named OnInitializedAsync was around 400.
The unique number of the methods (DeclaringType.FullName + Name) in my case was around 10000.

The execution time of the `AddFluxor()` method was reduced to approx. 10 seconds, when e.g. in https://github.com/mrpmorris/Fluxor/blob/3.1.1/Source/Fluxor/DependencyInjection/DependencyScanner.cs to local IEnumerable variables definition I added `.ToList()` at the end.

On a smaller scale, the problem can be reproduced, e.g. by cloning the repository https://github.com/SamProf/MatBlazor and adding the Fluxor in MatBlazor.Demo.ClientApp project:
`builder.Services.AddFluxor (o => o.ScanAssemblies (typeof (MatBlazor.Demo.Components.BaseDocComponent) .Assembly));`
- this takes about 10seconds...

Can assembly scanning be improved somehow?

**Comment by mrpmorris** [comment]
This has been fixed in 3.2 - please let me know how you get on, and thank you for reporting the problem!

**Comment by szmalec** [comment]
New version 3.2 improved setup process - execution time for `services.AddFluxor method (options => options.ScanAssemblies (typeof(Program).Assembly))` has been reduced to about **2500ms**!

Additional observations:
- When I use the source code references instead of the Nuget package references and when I disable the `DiscoverEffectMethods` and `DiscoverReducerMethods `methods, the execution time in my project is about **240ms**.
- When I turn off only one of the mentioned methods, the time is approx. **1500ms**.
- When I slightly modify both methods by adding the code:
`var excludeDeclaringTypes = new[] {typeof(object).FullName, "Microsoft.AspNetCore.Components.ComponentBase", "MyBlazorApp.Web.Client.Components.MyBlazorAppComponentBase"};`
and in [this line](https://github.com/mrpmorris/Fluxor/blob/3.2/Source/Fluxor/DependencyInjection/DependencyScanners/ReducerMethodsDiscovery.cs#L17) I will insert a condition:
`.Where (m =>! ExcludeDeclaringTypes.Contains(m.DeclaringType.FullName))`
then the time is approx. **2000ms** (500ms better than unchanged).
In my case, the use of this additional filtering reduces the number of methods from 27845 to 10780. I can send you (e.g. on a private conversation on gitter) a text file with a logs to which I dumped all these method names with DeclaringTypes - maybe take a look at them will result in an idea for optimization or suggestions on what I could change to speed up the process ...
-  When I modify `DiscoverEffectMethods` and `DiscoverReducerMethods` so that they take the `IEnumerable<MethodInfo> allCandidateTypesMethods` parameter instead of the `IEnumerable<Type> allCandidateTypes` parameter and set this parameter in `DependencyScanner` like this:
```
var allCandidateTypesMethods = allCandidateTypes
    .SelectMany(t => t.GetMethods(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.Static))
    .ToArray();
```
the time is approx. **2200ms**.
- When, in addition to the above solution, I add a condition that excludes certain types (see the `excludeDeclaringTypes` variable), the time is reduced to **1600ms**.
- If, as in the above solution, instead of the `excludeDeclaringTypes` condition, I will add filtering by attributes:
`.Where(m => m.GetCustomAttributes(false).Any(attr => attr is ReducerMethodAttribute || attr is EffectMethodAttribute))`
the time is **1000-1100ms**!


I performed all test runs from VisualStudio in Debug mode.

As you can see, the best result was achieved by modifying `DependencyScanner` in such a way that the `Scan` method filters the methods that are then passed to `ReducerMethodsDiscovery.DiscoverReducerMethods` / `EffectMethodsDiscovery.DiscoverEffectMethods`:

```
var allCandidateTypesMethods = allCandidateTypes
	.SelectMany(t => t.GetMethods(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.Static))
	//.Where(m => !excludeDeclaringTypes.Contains(m.DeclaringType.FullName))	// this does not improves if used with subsequent condition (with GetCustomAttributes)
	.Where(m => m.GetCustomAttributes(false).Any(attr => attr is ReducerMethodAttribute || attr is EffectMethodAttribute))
	//.Where(m => m.GetCustomAttributes<ReducerMethodAttribute>(false) != null || m.GetCustomAttributes<EffectMethodAttribute>(false) != null)	// 3000ms !!!
	.ToArray();

// ...

IEnumerable<DiscoveredReducerMethod> discoveredReducerMethods =
	ReducerMethodsDiscovery.DiscoverReducerMethods(serviceCollection, allCandidateTypesMethods);//ReducerMethodsDiscovery.DiscoverReducerMethods(serviceCollection, allCandidateTypes);

// ...

IEnumerable<DiscoveredEffectMethod> discoveredEffectMethods = 
	EffectMethodsDiscovery.DiscoverEffectMethods(serviceCollection, allCandidateTypesMethods);

```
The disadvantage of this solution is probably that it is not as "clean" / "elegant" (SRP) as the currently used...
I was wondering whether not to take things related to Fluxor into a separate project - but while in the case of ReducerMethod I do not see any obstacles (because they should not have dependencies), but in the case of EffectMethods there are dependencies on, for example, services used to fetch data, so probably also I would have to move them outside the main application...

**Comment by mrpmorris** [comment]
I'm have a look over the weekend

**Comment by mrpmorris** [comment]
Thank you for all your help on this!

**Comment by mrpmorris** [comment]
All speed improvements are now in release 3.3
