### ISSUE TITLE
Dispatching actions from Devtools does not work

### ISSUE THREAD

**Issue by Plasmadog** [mrpmorris/Fluxor#73]
Should it be possible to dispatch actions from the DevTools? I cannot get it to work, but is that expected?

I have followed the tutorial, so I have the IncrementCounterAction wired up, but nothing I have entered on the dispatcher tab has any effect when I click the dispatch button. I don't even get any error messages.

Is this a bug or just missing documentation?

**Comment by mrpmorris** [comment]
I didn't even know it was possible to dispatch from devtools, so I haven't implemented it.

I'm not actually sure I could implement it on account I wouldn't know what type of object to deserialise the json to.
