### ISSUE TITLE
LayoutsComponentsBase

### ISSUE THREAD

**Issue by wichur** [mrpmorris/Fluxor#8]
Hi! 

**Great job with Fluxor!**

I'm playing around with Blazor WASM 3.2.0 rev2 and found out something that might be an issue or my misunderstanding.

### Problem
I've created couple of FluxorComponents. Everything works very well. But when I've placed one in MainLayout.razor its not refreshing itself after action dispatched form OnInitialized (Async too). I've moved it to Index.razor and inherited from FluxorComponent and it works again. Maybe base class for layouts could help?

Best regards
MR

**Comment by mrpmorris** [comment]
Will do. May as well change the subscription code to use delegates for speed instead of reflection.

**Comment by mrpmorris** [comment]
Try pre-release 3.1.0-Pre-2 and let me know how you get on

**Comment by wichur** [comment]
Now everything updates nicely :)

**Comment by mrpmorris** [comment]
#

**Comment by mrpmorris** [comment]
Thanks for letting me know!
