### ISSUE TITLE
Add needed base calls when using FluxorComponent

### ISSUE THREAD

**Issue by serge-wq** [mrpmorris/Fluxor#82]
I was having some issues when disposing a Component that inherited from FluxorComponent until I realized I didn't call base.OnInitialized when overriding the method. This caused the subscription that is disposed later to be null triggering the exception. I'm creating this issue just to suggest that maybe it would be a good idea to add the remark that a call to base.OnInitialized is **needed** when using FluxorComponent and overriding OnInitialized.

Great work with the library.

**Comment by mrpmorris** [comment]
Yes, that seems like a good idea. If you'd like to submit a PR, I'd be happy to look at it.

```
if (whatever == null)
  throw new NullReferenceException($"{nameof(whatever)} is null. Either the constructor failed, or an OnInitialized method has been overridden that does not call the base method");
```
