### ISSUE TITLE
May I use Fluxor in my book ?

### ISSUE THREAD

**Issue by hybrid-technologies-solutions** [mrpmorris/Fluxor#88]
Hi @mrpmorris 

I plan to write a book in french for Blazor.
In a dedicated chapter, I want to talk about Redux pattern and how to use it with Blazor.
As I'm currently using Fluxor for a project, my editor needs me to ask : can I speak about Fluxor in my book and how to use it ?

Thanks for answering !

**Comment by mrpmorris** [comment]
Absolutely! I'd like to see a link to the book when done 👍

**Comment by cdie** [comment]
Hi @mrpmorris 

The book is finished and now published ;-)
You can find a french description here : https://www.editions-eni.fr/livre/blazor-developpement-front-end-d-applications-web-dynamiques-en-c-9782409030260

Chapter 5 covers Redux/Flux, with manual implementation and then, showing my readers how Fluxor can simplify their lives !

Thanks for the lib :-)

**Comment by mrpmorris** [comment]
Thanks for letting me know!

Would your publisher allow you to privately send me the contents of that chapter?
