### ISSUE TITLE
No parameterless constructor defined for type 'FluxorTest.App'

### ISSUE THREAD

**Issue by MrYossu** [mrpmorris/Fluxor#89]
Hello,

I'm brand new with Fluxor, so please forgive me if I'm doing something stupid.

I'm trying to follow the [first tutorial](https://github.com/mrpmorris/Fluxor/blob/master/Tutorials/01-BasicConcepts/01A-StateActionsReducersTutorial/README.md), and am getting a compilation error.

I added the package, then added the following two lines to the `ConfigureServices` method in `Startup.cs`...

      services.AddScoped<App>();
      services.AddFluxor(o => o
        .ScanAssemblies(typeof(Program).Assembly));

I know the tutorial says to put them in `Program.cs`, but it didn't seem to make any difference, and everything else I've seen says to add your services in `Startup.cs`

I then added a class called `App` and copied in the code. At this point, I tried to run the project, but had an error in the browser window of "No parameterless constructor defined for type 'FluxorTest.App'" which makes sense, as there isn't one.

What did I do wrong? Thanks

**Comment by mrpmorris** [comment]
The section 1 tutorials are basic concepts and use Console applications.

If you want to go straight into Blazor tutorials, start here instead - https://github.com/mrpmorris/Fluxor/tree/master/Tutorials/02-Blazor

**Comment by MrYossu** [comment]
Duh, silly me, I didn't notice that!

Thanks
