### ISSUE TITLE
Incorrect code in the State, Actions, and Reducers tutorial

### ISSUE THREAD

**Issue by MrYossu** [mrpmorris/Fluxor#92]
Just going through the tutorials, and have noticed what seems to be a mistake.

In the Tips section of [Fluxor/Tutorials/02-Blazor/02A-StateActionsReducersTutorial](https://github.com/mrpmorris/Fluxor/tree/master/Tutorials/02-Blazor/02A-StateActionsReducersTutorial#tips), there are four methods that look like this...

````c#
[ReducerMethod]
public static SomeState(SomeState state, SomeAction action) => new SomeState();
````

Shouldn't these be more like this...

````c#
[ReducerMethod]
public static SomeState DoSomething(SomeState state, SomeAction action) => new SomeState();
````

The code as shown doesn't compile, unless I've missed something obvious (quite possible at this time of night!)

The same applies in the [01 tutorials section](https://github.com/mrpmorris/Fluxor/tree/master/Tutorials/01-BasicConcepts/01A-StateActionsReducersTutorial#tips).

**Comment by mrpmorris** [comment]
Thank you!

**Comment by MrYossu** [comment]
@mrpmorris My pleasure. I'm trying to learn this package (and pattern), so may have some more comments from a newbie's point of view 😀

Thanks for all the hard work you've put in to creating and maintaining it.

**Comment by mrpmorris** [comment]
Fixed!
