### ISSUE TITLE
Why is the counter state saved in the store, but not the weather forecasts?

### ISSUE THREAD

**Issue by MrYossu** [mrpmorris/Fluxor#94]
Still following the Blazor web tutorials (done the [second one](https://github.com/mrpmorris/Fluxor/tree/master/Tutorials/02-Blazor/02B-EffectsTutorial) now), and I've noticed that when you click away from the counter page and then click back, the counter state is preserved, so if I click the button to increase the counter a few times, go to another page and come back, the number is the same as it was before, not reset to zero.

However, if I do the same with the fetch data page, the weather forecasts are reloaded. I noticed this as I was looking at what the IsLoading property was doing, and added a delay when loading the weather data. This allowed me to see the "Loading..." message, but also clarified that the data was reloaded every time I went back to the page.

How do I make it so that the weather data is also saved in the store and not reloaded? Thanks

**Comment by mrpmorris** [comment]
There is a reducer that sets forecasts to null, change it to state.Forecasts if you want to keep the forecasts from the previous state.

**Comment by MrYossu** [comment]
@mrpmorris Hello again and thanks for the reply.

Unfortunately, that didn't work. When I clicked to another page and clicked back, it reloaded the forecasts.

Any idea? Thanks

**Comment by mrpmorris** [comment]
That's because the page dispatches an action to go and fetch the data. You'd have to change the page to only ask if it needs it.

**Comment by MrYossu** [comment]
@mrpmorris Thanks, obvious when you point it out!

I think I was assuming there was something in the flux pipeline that would take care of this, as opposed to having logic in the razor view (which this pattern seems to minimise).

Thanks again
