### ISSUE TITLE
Feature base constructor prevents injected service usage

### ISSUE THREAD

**Issue by Elfocrash** [mrpmorris/Fluxor#97]
Hey 👋 

I've been trying to build something with Fluxor and I encountered a weird issue which i am not sure whether it's intended or not.

Assume the following:

Logger is a custom logger, nothing to do with Serilog or MS Logger. It just holds a stream of logs in memory.
```
public class LoggerFeature : Feature<LoggerState>
    {
        private readonly Logger _logger;

        public LoggerFeature(Logger logger)
        {
            _logger = logger;
        }

        public override string GetName() => "Logger";

        protected override LoggerState GetInitialState() => new LoggerState(_logger.Logs);
    }
```

The LoggerFeature is used in a Logger component which is used to display some logs. 
Since I won't want the logs to be cleared on page reload I am initializing the state via the singleton Logger that I am injecting.
The problem is that this doesn't work because in the abstract class `Feature`'s ctor there is a `public Feature() => this.State = this.GetInitialState();` which will execute before my services are properly injected and it will cause an NRE here `new LoggerState(_logger.Logs);`.

I am currently hacking around it by doing this:

```
public sealed class LoggerFeature : Feature<LoggerState>
    {
        public LoggerFeature(Logger logger)
        {
            State = new LoggerState(logger.Logs);
        }

        public override string GetName() => "Logger";

        protected override LoggerState GetInitialState() => null;
    }
```

which as you can tell, is quite ugly and I don't feel good about it.

Am I missing something or is there a proper alternative for this?

Thanks

**Comment by mrpmorris** [comment]
Features aren't supposed to do anything other than describe a set of state.

I'm not really following what you are trying to do.

**Comment by Elfocrash** [comment]
I am trying to initialise the state of the component based on a value that lives withing a registered singleton in my DI.

**Comment by mrpmorris** [comment]
Have an effect that reacts to StoreInitializedAction. Inject your DI into that. When it experiences the action have it dispatch some kind of InitializeMyStateAction that has all the data in that your reducer needs to put into state.

**Comment by Elfocrash** [comment]
Gotcha, thanks!

**Comment by sixpeteunder** [comment]
@mrpmorris I'm just getting started with Fluxor and I'm trying to accomplish something similar, could I get a sample of what the code for this would look like?

**Comment by mrpmorris** [comment]
```
public class MyEffect : Effect <SomeAction>
{
  // add a constructor with dependencis for parameters

  // Override HandleAsync and use them
}
```

**Comment by sixpeteunder** [comment]
Thank you, I managed to get it working.
