### ISSUE TITLE
Parameterised injected state ?

### ISSUE THREAD

**Issue by RenaudGelai** [mrpmorris/Fluxor#98]
Hello,

I'm working on a home automation system for my house.

It is a windows service writen in C#, and it exposes a grpc endpoint to a blazor server-side project that is the GUI.

I'm willing to use fluxor for this project, but i encounter something where no simple solution comes to my mind.

I'll explain my problem with just on thing : lights management.

I have a page where all manageable devices are listed (only lights by now)
The list is not known at the compilation time of the balzor project, because it's configurable in the service.
So, the list is fetched from the grpc endpoint, and then i use RenderFragment to "instanciate" blazor components dynamicaly
![image](https://user-images.githubusercontent.com/998330/93352800-823cc100-f83b-11ea-8359-ce89b77badec.png)
ComponentName is the name of the hardware device ("BedroomMainLight" for exemple), and ComponentType is the type of the hardware device ("Light" or "DimmableLight" for now). 

So, what i have is a blazor components that holds its own state and communicates with the grpc endpoint directly.
![image](https://user-images.githubusercontent.com/998330/93353330-173fba00-f83c-11ea-8774-e69be9858ede.png)

I'd like to have a more professional approach, and use some state management framework.

I see that with fluxor, i could inject some ILightState, but how could i inject a different instance in every component (Scoped would not work) and how do i tell the state that it should handle the state of this one light and not an other.

I also would like to be able to drop this blazor component on any page, like on a dashboard for exemple.

Is there a way to do it cleanly ?

Thanks in advance.

Best regards.

**Comment by mrpmorris** [comment]
Hi

Instead of thinking of your state like this

Light Light;
Door Door;

Think of it like this

IEnumerable<ILight> Lights;
IEnumerable<IDoor> Doors;

If ILight and IDoor both have some kind of unique ID then you can manipulate the individual entry. This is really easy in .NET 5 with the record feature.

public record HomeState(IEnumerable<ILight> Lights);

[ActionReducer]
public HomeState Reduce(HomeState state, TurnOffLight action) =>
  state with
  {
    Lights = state.Lights.Select(light =>
      light.Id != action.LightId
      ? light
      : light with { IsOn = false })
  }

**Comment by RenaudGelai** [comment]
and what do i inject in the blazor component ?

**Comment by mrpmorris** [comment]
The component itself could have

```
[Parameter]
public string Id { get; set; }

[Inject]
private IState<HomeState> HomeState { get; set; }

private ILight Light => HomeState.Value.Lights[Id]; // Change the state from IEnumerable to IReadonlyDictionary<string, ILight> for performance.
```

Then your parent can do this

```
@foreach(ILight light in HomeState.Value.Lights)
{
  <LightComponent Id=@light.Id/>
}
```

**Comment by RenaudGelai** [comment]
Ok, thanks
