### ISSUE TITLE
How to maintain state when I refresh the page

### ISSUE THREAD

**Issue by Blackleones** [mrpmorris/Fluxor#99]
I am learning Flux pattern and I would like to create an app using Fluxor and Blazor Server-Side. 

### Some info about my problem context

Assume my app state has the following structure:

```csharp
public record AppState (LoadingStatus Status, IEnumerable<Post> Posts, int? SelectedPostId, string Error);
public record Post (int id, string title, string text);
public enum LoadingStatus { Idle, Loading, Succeeded, Failed };
```

- Users can see all the posts whenever they open the website landing on the index page. (*www.mySample.com*)
- Users can see post detail on another page that can be reached selecting one of the posts on the index page. (*www.mySample.com/post*)

My web app loads all the posts when the user opens the website and, after loaded, he can see them inside the index page.

When the user clicks on a post, my code calls the `SelectPostAction(int postId)` and the reducer will create a new state like

```json
{
    "Status": 2, 
    "Posts": [
        {"id": 1, "Title": "my title 1", "Text": "my text 1"},
        {"id": 2, "Title": "my title 2", "Text": "my text 2"}
    ],
    "SelectedPostId": 1,
    "Error": null
}
```

and then the following Effect is triggered letting the user navigate from *www.mySample.com* to *www.mySample.com/post* 

```csharp
public class OpenPostDetailEffect : Effect<SelectPostAction>
{
    private readonly NavigationManager _navigation;

    public OpenPostDetailEffect(NavigationManager navigation)
    {
        _navigation = navigation;
    }

    protected override Task HandleAsync(SelectPostAction action, IDispatcher dispatcher)
    {
        _navigation.NavigateTo("post");
        return Task.CompletedTask;
    }
}
```

And this is the detail page

```csharp
@page "/post"
@inherits FluxorComponent
@inject IState<AppState> AppState

<!-- post detail -->

@code {
    private Post Post;

    protected override OnInitialized() 
    {
        Post = AppState.Value.Posts.Single(p => p.Id == AppState.Value.SelectedPost);
        base.OnInitialized();
    }
}
```

### Problem

Everything works fine whenever the user uses the website, clicks on a post, and lets the app do the navigation on behalf of him. What happens if the user is watching a detailed post and decides to refresh the page? 

In that case `Post = AppState.Value.Posts.Single(p => p.Id == AppState.Value.SelectedPost)` throws an exception because `AppState.Posts` is empty. I think this problem is related to the `scoped` lifetime of `IState<T>` because Blazor creates a new instance when you open a new tab or refresh the page. 

Do you have any suggestions on how to solve this problem?

### Other notes

I have seen your [game](https://github.com/mrpmorris/the-periodic-table-of-elements-game) and you decided to manage the navigation with a state. I like your idea and I tried to use your project as a starting point. The problem now is that the user can not go back and forth using the browser arrows, that in my case it is nice user experience.

### Futher question

I am facing this problem even in Blazor Wasm. In this case, I would like to ask you if we could solve the problem by changing the `IState<T>` lifetime from `scoped` to `singleton`. What do you think about that?

**Comment by mrpmorris** [comment]
Refreshing the page is equivalent to closing an app and restarting it, so the in-memory state is lost.

If you want to allow the user to navigate to a specific post you'll need to write your app so that it expects the state to not be there.

I have the page fetch data from the server based on the Id. This is good practice in case another user has edited something.
